<br>

###   <font color="Coral">hw7pr2digits_modeler</font>
+ digits clasification -- and regression -- via NNets

Feel free to re-use your previous digits_cleaned.csv file 


### First, use the iris example to create a digit-predicting NNet

This is similar to the past two digits challenges, hw5 and hw6

**However**, because we're using NNets, you'll need to
+ create TEN categorical variables. You can use just one ``get_dummies`` pandas call
+ use a SCALER to make sure the network can, in a fair way, "hear" all of the inputs 

In [159]:
# libraries...
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)
# read data
filename = 'digits_cleaned.csv' # neighborhoods
df_tidy = pd.read_csv(filename)      # encoding = "utf-8", "latin1"
print(f"{filename} : file read into a pandas dataframe.")


# different version vary on how to see all rows (adapt to suit your system!)
#
print(f"df_tidy.shape is {df_tidy.shape}\n")
df_tidy.info()  # prints column information
df_tidy

digits_cleaned.csv : file read into a pandas dataframe.
df_tidy.shape is (1768, 65)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1768 entries, 0 to 1767
Data columns (total 65 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   pix0          1768 non-null   int64
 1   pix1          1768 non-null   int64
 2   pix2          1768 non-null   int64
 3   pix3          1768 non-null   int64
 4   pix4          1768 non-null   int64
 5   pix5          1768 non-null   int64
 6   pix6          1768 non-null   int64
 7   pix7          1768 non-null   int64
 8   pix8          1768 non-null   int64
 9   pix9          1768 non-null   int64
 10  pix10         1768 non-null   int64
 11  pix11         1768 non-null   int64
 12  pix12         1768 non-null   int64
 13  pix13         1768 non-null   int64
 14  pix14         1768 non-null   int64
 15  pix15         1768 non-null   int64
 16  pix16         1768 non-null   int64
 17  pix17         1768 non-n

pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...  pix55  \
0        0     0     9    14     8     1     0     0     0     0  ...      0   
1        0     0    11    12     0     0     0     0     0     2  ...      0   
2        0     0     1     9    15    11     0     0     0     0  ...      0   
3        0     0     0     0    14    13     1     0     0     0  ...      0   
4        0     0     5    12     1     0     0     0     0     0  ...      2   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...      0   
1764     0     0     6    16    13    11     1     0     0     0  ...      0   
1765     0     0     1    11    15     1     0     0     0     0  ...      0   
1766     0     0     2    10     7     0     0     0     0     0  ...      0   
1767     0     0    10    14     8     1     0     0     0     2  ...      0   

      pix56  pix57  pix58  pix59  pix60  pix61  pix62  pix63  actual_digit  
0         0      0     11     16     15     11      1      0             8  
1         0      0      9     12     13      3      0      0             9  
2         0      0      1     10     13      3      0      0             0  
3         0      0      0      1     13     16      1      0             1  
4         0      0      3     11      8     13     12      4             2  
...     ...    ...    ...    ...    ...    ...    ...    ...           ...  
1763      0      0      2     14     15      9      0      0             9  
1764      0      0      6     16     14      6      0      0             0  
1765      0      0      2      9     13      6      0      0             8  
1766      0      0      5     12     16     12      0      0             9  
1767      0      1      8     12     14     12      1      0             8  

[1768 rows x 65 columns]

In [160]:
#
# we need to make sure the categories are handed as categories!
#    scikit-learn calls these "dummy" variables:

df_tidy_cat = pd.get_dummies(data=df_tidy,prefix="is",columns=['actual_digit'])
df_tidy_cat

pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...   is_0  \
0        0     0     9    14     8     1     0     0     0     0  ...  False   
1        0     0    11    12     0     0     0     0     0     2  ...  False   
2        0     0     1     9    15    11     0     0     0     0  ...   True   
3        0     0     0     0    14    13     1     0     0     0  ...  False   
4        0     0     5    12     1     0     0     0     0     0  ...  False   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...  False   
1764     0     0     6    16    13    11     1     0     0     0  ...   True   
1765     0     0     1    11    15     1     0     0     0     0  ...  False   
1766     0     0     2    10     7     0     0     0     0     0  ...  False   
1767     0     0    10    14     8     1     0     0     0     2  ...  False   

       is_1   is_2   is_3   is_4   is_5   is_6   is_7   is_8   is_9  
0     False  False  False  False  False  False  False   True  False  
1     False  False  False  False  False  False  False  False   True  
2     False  False  False  False  False  False  False  False  False  
3      True  False  False  False  False  False  False  False  False  
4     False   True  False  False  False  False  False  False  False  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...  
1763  False  False  False  False  False  False  False  False   True  
1764  False  False  False  False  False  False  False  False  False  
1765  False  False  False  False  False  False  False   True  False  
1766  False  False  False  False  False  False  False  False   True  
1767  False  False  False  False  False  False  False   True  False  

[1768 rows x 74 columns]

In [161]:
#
# We've removed the irisname column, and with our "" 
# we don't need the irisnum of the columns need to be numeric, we'll drop irisname
ROW = 0
COLUMN = 1
df_model1 = df_tidy_cat # .drop('actual_digit', axis=COLUMN)
df_model1


pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...   is_0  \
0        0     0     9    14     8     1     0     0     0     0  ...  False   
1        0     0    11    12     0     0     0     0     0     2  ...  False   
2        0     0     1     9    15    11     0     0     0     0  ...   True   
3        0     0     0     0    14    13     1     0     0     0  ...  False   
4        0     0     5    12     1     0     0     0     0     0  ...  False   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...  False   
1764     0     0     6    16    13    11     1     0     0     0  ...   True   
1765     0     0     1    11    15     1     0     0     0     0  ...  False   
1766     0     0     2    10     7     0     0     0     0     0  ...  False   
1767     0     0    10    14     8     1     0     0     0     2  ...  False   

       is_1   is_2   is_3   is_4   is_5   is_6   is_7   is_8   is_9  
0     False  False  False  False  False  False  False   True  False  
1     False  False  False  False  False  False  False  False   True  
2     False  False  False  False  False  False  False  False  False  
3      True  False  False  False  False  False  False  False  False  
4     False   True  False  False  False  False  False  False  False  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...  
1763  False  False  False  False  False  False  False  False   True  
1764  False  False  False  False  False  False  False  False  False  
1765  False  False  False  False  False  False  False   True  False  
1766  False  False  False  False  False  False  False  False   True  
1767  False  False  False  False  False  False  False   True  False  

[1768 rows x 74 columns]

In [163]:
#
# once we have all the columns we want, let's create an index of their names...

#
# Let's make sure we have all of our helpful variables in one place 
#       To be adapted if we drop/add more columns...
#

#
# let's keep our column names in variables, for reference
#
COLUMNS = df_model1.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
  # It's a "pandas" list, called an Index
  # use it just as a Python list of strings:
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}\n\n")


#
# and our "species" names
#

# all of scikit-learn's ML routines need numbers, not strings
#   ... even for categories/classifications (like species!)
#   so, we will convert the flower-species to numbers:

SPECIES = ['0','1','2','3','4','5','6','7','8','9']   # int to str
SPECIES_INDEX = {'0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9}  # str to int

# Let's try it out...
for name in SPECIES:
    print(f"{name} maps to {SPECIES_INDEX[name]}")

COLUMNS is Index(['pix0', 'pix1', 'pix2', 'pix3', 'pix4', 'pix5', 'pix6', 'pix7', 'pix8',
       'pix9', 'pix10', 'pix11', 'pix12', 'pix13', 'pix14', 'pix15', 'pix16',
       'pix17', 'pix18', 'pix19', 'pix20', 'pix21', 'pix22', 'pix23', 'pix24',
       'pix25', 'pix26', 'pix27', 'pix28', 'pix29', 'pix30', 'pix31', 'pix32',
       'pix33', 'pix34', 'pix35', 'pix36', 'pix37', 'pix38', 'pix39', 'pix40',
       'pix41', 'pix42', 'pix43', 'pix44', 'pix45', 'pix46', 'pix47', 'pix48',
       'pix49', 'pix50', 'pix51', 'pix52', 'pix53', 'pix54', 'pix55', 'pix56',
       'pix57', 'pix58', 'pix59', 'pix60', 'pix61', 'pix62', 'pix63', 'is_0',
       'is_1', 'is_2', 'is_3', 'is_4', 'is_5', 'is_6', 'is_7', 'is_8', 'is_9'],
      dtype='object')

COLUMNS[0] is pix0

COL_INDEX is {'pix0': 0, 'pix1': 1, 'pix2': 2, 'pix3': 3, 'pix4': 4, 'pix5': 5, 'pix6': 6, 'pix7': 7, 'pix8': 8, 'pix9': 9, 'pix10': 10, 'pix11': 11, 'pix12': 12, 'pix13': 13, 'pix14': 14, 'pix15': 15, 'pix16': 16, 'pix17': 17, 'pix18':

In [164]:
#
# let's convert our dataframe to a numpy array, named A
#
A = df_model1.to_numpy()   
A = A.astype('float64')    # many types:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A[:,:])

# print(A)  # the five rows above is probably enough...  
# 
# #
# nice to have NUM_ROWS and NUM_COLS around
#
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols") 

[[ 0.  0.  9. ...  0.  1.  0.]
 [ 0.  0. 11. ...  0.  0.  1.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  1. ...  0.  1.  0.]
 [ 0.  0.  2. ...  0.  0.  1.]
 [ 0.  0. 10. ...  0.  1.  0.]]

The dataset has 1768 rows and 74 cols


In [165]:
# let's use all of our variables, to reinforce that we have
# (1) names...
# (2) access and control...

# choose a row index, n:
n = 47
print(f"digit #{n} is {A[n]}")
species = ""

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    value = A[n][i]
    print(f"  Its {colname} is {value}")
    if colname[:3] == 'is_':
        if value == 1:
            species = colname[3:]

print()
print(f"  and its species name: {species}")

digit #47 is [ 0.  1. 13. 15. 12. 12.  5.  0.  0.  4. 16.  8.  8.  6.  0.  0.  0.  7.
 13.  0.  0.  0.  0.  0.  0.  8. 15. 13. 15.  7.  0.  0.  0.  1.  6.  5.
  8. 12.  0.  0.  0.  0.  0.  0. 12. 11.  0.  0.  0.  0.  2. 13. 14.  1.
  0.  0.  0.  3. 14. 10.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.
  0.  0.]
  Its pix0 is 0.0
  Its pix1 is 1.0
  Its pix2 is 13.0
  Its pix3 is 15.0
  Its pix4 is 12.0
  Its pix5 is 12.0
  Its pix6 is 5.0
  Its pix7 is 0.0
  Its pix8 is 0.0
  Its pix9 is 4.0
  Its pix10 is 16.0
  Its pix11 is 8.0
  Its pix12 is 8.0
  Its pix13 is 6.0
  Its pix14 is 0.0
  Its pix15 is 0.0
  Its pix16 is 0.0
  Its pix17 is 7.0
  Its pix18 is 13.0
  Its pix19 is 0.0
  Its pix20 is 0.0
  Its pix21 is 0.0
  Its pix22 is 0.0
  Its pix23 is 0.0
  Its pix24 is 0.0
  Its pix25 is 8.0
  Its pix26 is 15.0
  Its pix27 is 13.0
  Its pix28 is 15.0
  Its pix29 is 7.0
  Its pix30 is 0.0
  Its pix31 is 0.0
  Its pix32 is 0.0
  Its pix33 is 1.0
  Its pix34 is 6.0
  Its pix35 is 5.0
  

In [166]:
print("+++ Start of data definitions +++\n")

#
# we could do this at the data-frame level, too!
#

X_all = A[:,0:64]   # X (features) ... is all rows, columns 0, 1, 2, 3
y_all = A[:,64:]    # y (labels) ... is all rows, columns 4, 5, and 6

print(f"y_all (just the labels/species, first few rows) are \n {y_all[0:5]}")
print()
print(f"X_all (just the features, first few rows) are \n {X_all[0:5]}")

+++ Start of data definitions +++

y_all (just the labels/species, first few rows) are 
 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]

X_all (just the features, first few rows) are 
 [[ 0.  0.  9. 14.  8.  1.  0.  0.  0.  0. 12. 14. 14. 12.  0.  0.  0.  0.
   9. 10.  0. 15.  4.  0.  0.  0.  3. 16. 12. 14.  2.  0.  0.  0.  4. 16.
  16.  2.  0.  0.  0.  3. 16.  8. 10. 13.  2.  0.  0.  1. 15.  1.  3. 16.
   8.  0.  0.  0. 11. 16. 15. 11.  1.  0.]
 [ 0.  0. 11. 12.  0.  0.  0.  0.  0.  2. 16. 16. 16. 13.  0.  0.  0.  3.
  16. 12. 10. 14.  0.  0.  0.  1. 16.  1. 12. 15.  0.  0.  0.  0. 13. 16.
   9. 15.  2.  0.  0.  0.  0.  3.  0.  9. 11.  0.  0.  0.  0.  0.  9. 15.
   4.  0.  0.  0.  9. 12. 13.  3.  0.  0.]
 [ 0.  0.  1.  9. 15. 11.  0.  0.  0.  0. 11. 16.  8. 14.  6.  0.  0.  2.
  16. 10.  0.  9.  9.  0.  0.  1. 16.  4.  0.  8.  8.  0.  0.  4. 16.  4.
   0.  8.  8.  0. 

In [167]:
#
# we can scramble the data, to remove (potential) dependence on its ordering: 
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print(f"The scrambled labels/species are \n {y_all[0:5]}")
print()
print(f"The corresponding data rows are \n {X_all[0:5]}")

The scrambled labels/species are 
 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

The corresponding data rows are 
 [[ 0.  0.  9. 16. 16. 13.  1.  0.  0.  0. 12. 13. 14. 16.  7.  0.  0.  0.
   0.  0.  6. 16.  4.  0.  0.  0.  0.  0. 13. 14.  1.  0.  0.  0.  1. 10.
  16.  6.  0.  0.  0.  0.  7. 16.  8.  0.  0.  0.  0.  2. 15. 16. 12.  7.
   0.  0.  0.  0.  9. 14. 16. 16.  2.  0.]
 [ 0.  1.  9. 16. 16. 15.  3.  0.  0.  8. 16. 12.  8.  8.  3.  0.  0.  6.
  16.  9.  3.  0.  0.  0.  0.  8. 16. 16. 16.  4.  0.  0.  0.  3.  6.  4.
  13. 11.  0.  0.  0.  0.  0.  0.  8. 13.  0.  0.  0.  0.  5.  8. 15. 10.
   0.  0.  0.  0. 11. 16. 11.  1.  0.  0.]
 [ 0.  2. 13. 16. 16. 11.  0.  0.  0. 10. 11.  4. 12. 12.  0.  0.  0.  1.
   1.  4. 14.  8.  0.  0.  0.  0.  2. 16. 16.  8.  0.  0.  0.  0.  0.  7.
   9. 16.  8.  0.  0.  0.  0.  0.  0. 10. 12.  0.  0.  0.  5.  9. 10. 16.
   9.  0.  0

In [168]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"+++ Testing +++   Held-out data... (testing data: {len(y_test)})\n")
print(f"y_test: {y_test[0:5,:]}\n")
print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
print("\n")
print(f"+++ Training +++   Data used for modeling... (training data: {len(y_train)})\n")
print(f"y_train: {y_train[0:5,:]}\n")
print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows

training with 1414 rows;  testing with 354 rows

+++ Testing +++   Held-out data... (testing data: 354)

y_test: [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

X_test (few rows): [[ 0.  0.  4. 15. 13.  3.  0.  0.  0.  1. 16. 13. 16. 15.  1.  0.  0.  6.
  15.  0.  4. 16.  4.  0.  0.  3. 15. 14. 16. 14.  0.  0.  0.  0.  4. 16.
  16. 11.  0.  0.  0.  0. 11. 12.  8. 16.  5.  0.  0.  0. 16. 10. 12. 16.
   3.  0.  0.  0.  7. 16. 13.  7.  0.  0.]
 [ 0.  0.  1.  8. 16.  7.  0.  0.  0.  0.  3. 16. 16. 12.  0.  0.  0.  1.
  15. 16. 16. 12.  0.  0.  0.  3. 12. 15. 16. 12.  0.  0.  0.  0.  0.  8.
  16. 10.  0.  0.  0.  0.  0. 11. 16. 14.  0.  0.  0.  0.  0. 11. 16. 16.
   1.  0.  0.  0.  0.  5. 13.  7.  0.  0.]
 [ 0.  0.  2. 10. 16. 11.  1.  0.  0.  0. 13. 13. 10. 16.  8.  0.  0.  4.
  14.  1.  8. 14.  1.  0.  0.  4. 15. 12. 15.  8.  0.  0.  0.  0.  6.  7.
  14.  5.  0.  0.  0.  

In [170]:
#
# for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
#    This is done through the "StandardScaler" in scikit-learn
# 
from sklearn.preprocessing import StandardScaler

#
# do we want to use a Scaler?
#
USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    scaler = StandardScaler()
    scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
else:
    # this one does no scaling!  We still create it to be consistent:
    scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
    scaler.fit(X_train)  # still need to fit, though it does not change...

scaler   # is now defined and ready to use...

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Here are our scaled training and testing sets:

X_train_scaled = scaler.transform(X_train) # scale!
X_test_scaled = scaler.transform(X_test) # scale!

y_train_scaled = y_train.copy()  # the predicted/desired labels are not scaled
y_test_scaled = y_test.copy()  # not using the scaler



In [171]:
#
# let's create a table for showing our data and its predictions...
#
def ascii_table(X,y,scaler_to_invert=None):
    """ print a table of inputs and outputs """
    np.set_printoptions(precision=2)  # Let's use less precision
    if scaler_to_invert == None:  # don't use the scaler
        X = X
    else:
        X = scaler_to_invert.inverse_transform(X)
    print(f"{'input ':>58s} -> {'pred':^7s} {'des':<5s}") 
    for i in range(len(y)):
        # whoa! serious f-string formatting:
        print(f"{str(X[i,0:4]):>58s} -> {'?':^7s} {str(y[i]):<21s}")   # !s is str ...
    print()
    
# to show the table with the scaled data:
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

# to show the table with the original data:
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler_to_invert=scaler)

                                                    input  ->  pred   des  
                                     [0.   7.27 2.25 0.96] ->    ?    [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
                                 [ 0.   -0.34 -1.11 -0.94] ->    ?    [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
                                 [ 0.   -0.34  1.2   0.96] ->    ?    [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
                                 [ 0.   -0.34 -0.27  0.72] ->    ?    [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
                                     [0.   0.75 1.83 0.96] ->    ?    [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]

                                                    input  ->  pred   des  
                                         [ 0.  7. 16. 16.] ->    ?    [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
                                             [0. 0. 0. 8.] ->    ?    [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
                                         [ 0.  0. 11. 16.] ->    ?    [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
                               

In [172]:
from sklearn.neural_network import MLPClassifier

#
# Here's where you can change the number of hidden layers
# and number of neurons!  It's in the tuple  hidden_layer_sizes:
#
nn_classifier = MLPClassifier(hidden_layer_sizes=(6,7),  
                    # hidden_layer_sizes=(6,7)   means   4 inputs -> 6 hidden -> 7 hidden -> 3 outputs
                    max_iter=500,      # how many times to train
                    # activation="tanh", # the "activation function" input -> output
                    # solver='sgd',      # the algorithm for optimizing weights
                    verbose=True,      # False to "mute" the training
                    shuffle=True,      # reshuffle the training epochs?
                    random_state=None, # set for reproduceability
                    learning_rate_init=.1,       # learning rate: the amt of error to backpropagate!
                    learning_rate = 'adaptive')  # soften feedback as it converges

# documentation:
# scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html 
#     Try other network sizes / other parameters ...

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_classifier.fit(X_train_scaled, y_train_scaled)
print("\n++++++++++  TRAINING:   end  +++++++++++++++")
print(f"The analog prediction error (the loss) is {nn_classifier.loss_}")



++++++++++  TRAINING:  begin  +++++++++++++++


Iteration 1, loss = 4.28564369
Iteration 2, loss = 2.32837004
Iteration 3, loss = 1.86320863
Iteration 4, loss = 1.57356043
Iteration 5, loss = 1.39464675
Iteration 6, loss = 1.33464175
Iteration 7, loss = 1.29760083
Iteration 8, loss = 1.19766866
Iteration 9, loss = 1.08508405
Iteration 10, loss = 0.98113085
Iteration 11, loss = 1.00304719
Iteration 12, loss = 0.86860378
Iteration 13, loss = 0.89735286
Iteration 14, loss = 0.85092938
Iteration 15, loss = 0.78043088
Iteration 16, loss = 0.68974534
Iteration 17, loss = 0.73396525
Iteration 18, loss = 0.67037512
Iteration 19, loss = 0.61436931
Iteration 20, loss = 0.65820792
Iteration 21, loss = 0.57602157
Iteration 22, loss = 0.61854597
Iteration 23, loss = 0.63977833
Iteration 24, loss = 0.60687418
Iteration 25, loss = 0.64566976
Iteration 26, loss = 0.54133337
Iteration 27, loss = 0.48073061
Iteration 28, loss = 0.42153527
Iteration 29, loss = 0.72751614
Iteration 30, loss = 0.85929270

In [173]:
#
# how did it do on the testing data?
#

def get_species(A):
    """ returns the species for A ~ [1 0 0] or [0 1 0] or ... """
    for i in range(len(SPECIES)):
        if A[i] == 1: 
            return SPECIES[i]  # note that this "takes the first one"
    return "no species" 

SEE_PROBS = False

def ascii_table_for_classifier(Xsc,y,nn,scaler):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(Xsc)            # all predictions
    prediction_probs = nn.predict_proba(Xsc) # all prediction probabilities
    Xpr = scaler.inverse_transform(Xsc)      # Xpr is the "X to print": the unscaled data
    # count correct
    num_correct = 0
    # printing
    print(f"{'input ':>28s} -> {'pred':^12s} {'des.':^12s}") 
    for i in range(len(y)):
        pred = predictions[i]
        pred_probs = str(prediction_probs[i,:])
        desired = y[i].astype(int)
        # print(pred, desired, pred_probs)
        pred_species = get_species(pred)
        des_species  = get_species(desired)
        if pred_species != des_species: result = "  incorrect: " + pred_probs
        else: result = "  correct" + (": "+pred_probs if SEE_PROBS else "") ; num_correct += 1
        # Xpr = Xsc  # if you want to see the scaled versions
        print(f"{Xpr[i,0:4]!s:>28s} -> {pred_species:^12s} {des_species:12s} {result:^10s}") 
    print(f"\ncorrect predictions: {num_correct} out of {len(y)}")
    
#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_classifier(X_test_scaled,
                           y_test_scaled,
                           nn_classifier,
                           scaler)   


                      input  ->     pred         des.    
           [ 0.  0.  4. 15.] ->      8       8              correct 
               [0. 0. 1. 8.] ->      1       1              correct 
           [ 0.  0.  2. 10.] ->  no species  9              incorrect: [5.69e-06 9.39e-10 5.96e-11 5.17e-03 9.52e-06 3.69e-02 5.82e-11 2.18e-04
 4.79e-04 4.70e-01]
           [ 0.  0.  1. 10.] ->      4       4              correct 
           [ 0.  0.  3. 11.] ->      0       0              correct 
           [ 0.  0.  3. 13.] ->      8       8              correct 
           [ 0.  0.  2. 13.] ->      6       6              correct 
           [ 0.  0.  0. 11.] ->      6       6              correct 
               [0. 0. 2. 9.] ->      0       0              correct 
               [0. 0. 3. 8.] ->      1       1              correct 
               [0. 0. 0. 4.] ->      1       1              correct 
           [ 0.  0.  2. 11.] ->      8       8              correct 
           [ 0.  0.

In [174]:
#
# We don't usually look inside the NNet, but we can: it's open-box modeling...
#
if True:  # do we want to see all of the parameters?
    np.set_printoptions(precision=2)  # Let's use less precision
    nn = nn_classifier  # less to type?
    print("\n\n+++++ parameters, weights, etc. +++++\n")
    print(f"\nweights/coefficients:\n")
    for i, wts in enumerate(nn.coefs_):
        print(f"[[ Layer {i} ]]\n   has shape = {wts.shape} and weights =\n{wts}")
        print(f"   with intercepts:\n {nn.intercepts_[i]}\n")
    print()
    print(f"\nall parameters: {nn.get_params()}")



+++++ parameters, weights, etc. +++++


weights/coefficients:

[[ Layer 0 ]]
   has shape = (64, 6) and weights =
[[-3.87e-03 -2.69e-03  8.38e-04  3.71e-03 -1.78e-03 -6.94e-04]
 [ 6.31e-01 -3.33e-02  1.14e-01 -9.42e-01 -1.24e+00  6.86e-01]
 [-6.92e-01 -1.23e+00  1.54e+00  4.51e-01 -1.26e+00 -1.17e+00]
 [ 9.38e-01 -6.95e-01 -6.63e-02 -6.02e-01 -1.61e+00  6.95e-01]
 [ 4.23e-01  4.03e-01  1.38e+00  1.37e+00 -4.33e-01 -2.56e+00]
 [-2.96e+00 -1.77e+00  1.69e+00 -1.19e+00 -4.18e+00  4.18e-01]
 [-2.27e+00  8.84e-02  1.34e+00 -2.26e-01 -2.22e+00 -2.06e-01]
 [ 5.27e-01  1.19e+00  1.75e-01  4.90e-02  1.16e+00 -3.15e-01]
 [-7.06e-01 -5.55e-01 -6.37e-01 -1.72e-01 -1.04e+00  3.93e-03]
 [-1.24e-01  1.67e+00 -5.14e-01  6.32e-01 -1.89e-03 -6.11e-01]
 [-3.32e-01  1.11e+00  2.36e+00  2.18e+00 -1.14e+00 -1.62e+00]
 [ 2.84e-01 -2.78e-01  2.80e+00 -3.06e-01 -2.49e-01  4.80e-01]
 [ 6.86e-01  2.08e-01  1.45e+00  3.18e-01 -1.05e+00  6.50e-01]
 [ 6.94e-01 -4.83e-01 -9.26e-01  2.66e-01 -2.03e-01  5.94e-01]
 [

In [120]:
#
# final predictive model (random forests), with tuned parameters + ALL data incorporated
#

def get_species(A):
    """ returns the species for A ~ [1 0 0] or [0 1 0] or ... """
    for i in range(len(SPECIES)):
        if A[i] == 1: 
            return SPECIES[i]  # note that this "takes the first one"
    return "no species" 


def predictive_model( Features, MODEL, SCALER ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    scaled_features = SCALER.transform(our_features)      # we have to scale the features into "scaled space"
    predicted_cat = MODEL.predict(scaled_features)        # then, the nnet can predict our "cat" variables
    prediction_probs = nn.predict_proba(scaled_features) # all prediction probabilities
    # our_features = SCALER.inverse_transform(scaled_features)  # we can convert back (optional!)
    predicted_species = get_species(predicted_cat[0])     # (it's extra-nested) get the species name
    return predicted_species, prediction_probs
   
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [6.7,3.3,5.7,0.1]  # [5.8,2.7,4.1,1.0] [4.6,3.6,3.0,2.2] [6.7,3.3,5.7,2.1]

LoD = [[0,0,0,8,14,0,0,0,0,0,5,16,11,0,0,0,0,1,15,14,1,6,0,0,0,7,16,5,3,16,8,0,0,8,16,8,14,16,2,0,0,0,6,14,16,11,0,0,0,0,0,6,16,4,0,0,0,0,0,10,15,0,0,0],
[0,0,0,5,14,12,2,0,0,0,7,15,8,14,4,0,0,0,6,2,3,13,1,0,0,0,0,1,13,4,0,0,0,0,1,11,9,0,0,0,0,8,16,13,0,0,0,0,0,5,14,16,11,2,0,0,0,0,0,6,12,13,3,0],
[0,0,0,3,16,3,0,0,0,0,0,12,16,2,0,0,0,0,8,16,16,4,0,0,0,7,16,15,16,12,11,0,0,8,16,16,16,13,3,0,0,0,0,7,14,1,0,0,0,0,0,6,16,0,0,0,0,0,0,4,14,0,0,0],
[0,0,0,3,15,10,1,0,0,0,0,11,10,16,4,0,0,0,0,12,1,15,6,0,0,0,0,3,4,15,4,0,0,0,0,6,15,6,0,0,0,4,15,16,9,0,0,0,0,0,13,16,15,9,3,0,0,0,0,4,9,14,7,0],
[0,0,0,3,16,3,0,0,0,0,0,10,16,11,0,0,0,0,4,16,16,8,0,0,0,2,14,12,16,5,0,0,0,10,16,14,16,16,11,0,0,5,12,13,16,8,3,0,0,0,0,2,15,3,0,0,0,0,0,4,12,0,0,0],
[0,0,7,15,15,4,0,0,0,8,16,16,16,4,0,0,0,8,15,8,16,4,0,0,0,0,0,10,15,0,0,0,0,0,1,15,9,0,0,0,0,0,6,16,2,0,0,0,0,0,8,16,8,11,9,0,0,0,9,16,16,12,3,0]]


SEE_PROBS = False

# run on each one:
for Features in LoD:
    MODEL = nn_classifier
    SCALER = scaler
    name, probs = predictive_model( Features, MODEL, SCALER )  # pass in the model, too!
    prob_str = "   with probs: " + str(probs) if SEE_PROBS == True else ""
    print(f"I predict {name:>12s} from the features {Features}  {prob_str}")    # Answers in the assignment...

I predict            4 from the features [0, 0, 0, 8, 14, 0, 0, 0, 0, 0, 5, 16, 11, 0, 0, 0, 0, 1, 15, 14, 1, 6, 0, 0, 0, 7, 16, 5, 3, 16, 8, 0, 0, 8, 16, 8, 14, 16, 2, 0, 0, 0, 6, 14, 16, 11, 0, 0, 0, 0, 0, 6, 16, 4, 0, 0, 0, 0, 0, 10, 15, 0, 0, 0]  
I predict            2 from the features [0, 0, 0, 5, 14, 12, 2, 0, 0, 0, 7, 15, 8, 14, 4, 0, 0, 0, 6, 2, 3, 13, 1, 0, 0, 0, 0, 1, 13, 4, 0, 0, 0, 0, 1, 11, 9, 0, 0, 0, 0, 8, 16, 13, 0, 0, 0, 0, 0, 5, 14, 16, 11, 2, 0, 0, 0, 0, 0, 6, 12, 13, 3, 0]  
I predict            4 from the features [0, 0, 0, 3, 16, 3, 0, 0, 0, 0, 0, 12, 16, 2, 0, 0, 0, 0, 8, 16, 16, 4, 0, 0, 0, 7, 16, 15, 16, 12, 11, 0, 0, 8, 16, 16, 16, 13, 3, 0, 0, 0, 0, 7, 14, 1, 0, 0, 0, 0, 0, 6, 16, 0, 0, 0, 0, 0, 0, 4, 14, 0, 0, 0]  
I predict            2 from the features [0, 0, 0, 3, 15, 10, 1, 0, 0, 0, 0, 11, 10, 16, 4, 0, 0, 0, 0, 12, 1, 15, 6, 0, 0, 0, 0, 3, 4, 15, 4, 0, 0, 0, 0, 6, 15, 6, 0, 0, 0, 4, 15, 16, 9, 0, 0, 0, 0, 0, 13, 16, 15, 9, 3, 0, 0, 0, 0, 4, 9, 14, 7,

### Second, from the iris example create a _pixel-predicting_ &nbsp; NNet

Choose a pixel to predict!
+ It _can_ be #42 -- or choose another one?!
+ This will be _regression_, not classification
+ It will show off NNets' ability to generate or "hallucinate" pixels/digits/images/etc.!
+ The _digit dreaming_ problem will extend this further...

<b>Predict-a-pixel</b> (regression)...
+ As the penultimate part of this digits-analysis with NNets, 
+ create a regressor that predicts pixel 42 from the other 63 pixels!
+ Remember that pixel 42 will be `A[:,42]`
+ and, the other 63, plus the digit-species, will be `np.concatenate((A[:,0:42], A[:,43:]),axis=1)`
+ see the iris_modeler for an example for the irises' botanical features...

# Pixel 42 prediction NNet

In [175]:
#
# What shall we predict today?
print(COL_INDEX)
print()
print(COLUMNS)

# Let's first predict sepal length ('sepallen', column index 0)

{'pix0': 0, 'pix1': 1, 'pix2': 2, 'pix3': 3, 'pix4': 4, 'pix5': 5, 'pix6': 6, 'pix7': 7, 'pix8': 8, 'pix9': 9, 'pix10': 10, 'pix11': 11, 'pix12': 12, 'pix13': 13, 'pix14': 14, 'pix15': 15, 'pix16': 16, 'pix17': 17, 'pix18': 18, 'pix19': 19, 'pix20': 20, 'pix21': 21, 'pix22': 22, 'pix23': 23, 'pix24': 24, 'pix25': 25, 'pix26': 26, 'pix27': 27, 'pix28': 28, 'pix29': 29, 'pix30': 30, 'pix31': 31, 'pix32': 32, 'pix33': 33, 'pix34': 34, 'pix35': 35, 'pix36': 36, 'pix37': 37, 'pix38': 38, 'pix39': 39, 'pix40': 40, 'pix41': 41, 'pix42': 42, 'pix43': 43, 'pix44': 44, 'pix45': 45, 'pix46': 46, 'pix47': 47, 'pix48': 48, 'pix49': 49, 'pix50': 50, 'pix51': 51, 'pix52': 52, 'pix53': 53, 'pix54': 54, 'pix55': 55, 'pix56': 56, 'pix57': 57, 'pix58': 58, 'pix59': 59, 'pix60': 60, 'pix61': 61, 'pix62': 62, 'pix63': 63, 'is_0': 64, 'is_1': 65, 'is_2': 66, 'is_3': 67, 'is_4': 68, 'is_5': 69, 'is_6': 70, 'is_7': 71, 'is_8': 72, 'is_9': 73}

Index(['pix0', 'pix1', 'pix2', 'pix3', 'pix4', 'pix5', 'pix6', 'pi

In [176]:
#
# Here we set up for a regression model that will predict 'pix42'  (column index 42)

print("+++ Start of data-assembly for feature-regression! +++\n")
# construct the correct X_all from the columns we want
X_all = np.concatenate( (A[:,0:42], A[:,43:]), axis=1)    # includes columns 1, 2, 3, and 4

y_all = A[:,42]                    # y (labels) ... is all of column 0, sepallen (sepal length) 
#                                 # change the line above to make other columns the target (y_all)
print(f"y_all is \n {y_all}")
print() 
print(f"X_all (the features, first few rows) is \n {X_all[:5,:]}")


+++ Start of data-assembly for feature-regression! +++

y_all is 
 [16.  0. 16. ... 16.  0. 16.]

X_all (the features, first few rows) is 
 [[ 0.  0.  9. 14.  8.  1.  0.  0.  0.  0. 12. 14. 14. 12.  0.  0.  0.  0.
   9. 10.  0. 15.  4.  0.  0.  0.  3. 16. 12. 14.  2.  0.  0.  0.  4. 16.
  16.  2.  0.  0.  0.  3.  8. 10. 13.  2.  0.  0.  1. 15.  1.  3. 16.  8.
   0.  0.  0. 11. 16. 15. 11.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
   0.]
 [ 0.  0. 11. 12.  0.  0.  0.  0.  0.  2. 16. 16. 16. 13.  0.  0.  0.  3.
  16. 12. 10. 14.  0.  0.  0.  1. 16.  1. 12. 15.  0.  0.  0.  0. 13. 16.
   9. 15.  2.  0.  0.  0.  3.  0.  9. 11.  0.  0.  0.  0.  0.  9. 15.  4.
   0.  0.  0.  9. 12. 13.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.]
 [ 0.  0.  1.  9. 15. 11.  0.  0.  0.  0. 11. 16.  8. 14.  6.  0.  0.  2.
  16. 10.  0.  9.  9.  0.  0.  1. 16.  4.  0.  8.  8.  0.  0.  4. 16.  4.
   0.  8.  8.  0.  0.  1.  5.  1. 11.  3.  0.  0.  0. 12. 12. 10. 10.  0.
   0.  0.  0.  1. 10. 13.  3.  0

In [154]:
#
# we scramble the data, to give a different TRAIN/TEST split each time...
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("target values to predict: \n",y_all)
print("\nfeatures (a few)\n", X_all[0:5,:])

target values to predict: 
 [14.  0.  8. ...  0.  3. 12.]

features (a few)
 [[ 0.  0.  1.  7.  6. 11.  1.  0.  0.  0. 13. 11. 15. 16.  7.  0.  0.  0.
  13.  6. 11. 16.  4.  0.  0.  0.  3. 15. 16.  7.  0.  0.  0.  0.  4. 15.
  14.  7.  0.  0.  0.  1.  3.  1. 13.  0.  0.  0.  2. 12.  2.  3. 12.  0.
   0.  0.  0.  1. 10.  8.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
   0.]
 [ 0.  0.  5. 12. 13.  3.  0.  0.  0.  4. 16.  9.  8. 12.  0.  0.  0.  2.
   3.  0.  5. 11.  0.  0.  0.  0.  0.  3. 11. 10.  0.  0.  0.  0.  0.  6.
  14. 15.  3.  0.  0.  0.  0.  0.  7. 11.  0.  0.  0. 10.  6.  4.  9. 11.
   0.  0.  0.  6. 16. 16. 14.  2.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.
   0.]
 [ 0.  0.  4. 14. 11.  3.  0.  0.  0.  0.  1. 15. 16.  6.  0.  0.  0.  0.
   0. 16. 16.  9.  0.  0.  0.  0.  1. 14. 16.  3.  0.  0.  0.  0.  6. 16.
  16.  2.  0.  0.  0.  0. 16. 15.  0.  0.  0.  0.  0.  7. 16. 11.  0.  0.
   0.  0.  0.  6. 15. 14.  4.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   0.]
 [ 0.  0.  3. 

In [177]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)})")
print(f"y_test: {y_test}\n")
print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)})")
print(f"y_train: {y_train}\n")
print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows

training with 1414 rows;  testing with 354 rows

Held-out data... (testing data: 354)
y_test: [16. 16.  0.  9. 16.  0. 14.  1.  0.  0.  8.  0.  0.  0.  4. 15. 12.  5.
  0.  7.  0.  0.  5. 14.  0.  0. 16. 15.  6.  0.  3.  0.  8.  0.  0.  0.
  0.  0.  3.  0.  0. 12. 14.  9.  0. 13.  0.  7. 16.  0.  2.  4. 16. 16.
 16.  0. 15.  0.  0.  0. 14. 16.  0. 15.  0.  0.  2.  2.  0.  5.  1. 16.
  3. 16.  9. 16.  0. 16.  6.  0. 12. 14.  0.  0.  3. 14.  0. 16. 15. 16.
  0.  0.  0.  0. 16.  0. 16. 16. 16.  0.  0.  1. 14. 10.  0. 16. 15.  0.
  0. 13. 12. 16.  0.  4.  0.  4. 14. 16.  0.  0. 16.  0.  8.  0.  0. 16.
 16. 16.  7.  0.  0. 16.  0. 16. 12.  5. 16.  0. 14.  5.  5. 16. 12.  0.
  4.  6. 12. 16. 13.  0.  8.  0.  3. 14. 14.  1. 11. 16. 16.  0.  4. 12.
  0.  5.  0. 16.  3.  1. 12.  0. 15. 15.  3. 10.  9.  6.  9. 16.  0.  0.
  0.  0.  6.  0. 12.  1. 10.  0. 10.  0. 13. 16. 12.  1. 16. 16. 16.  3.
  0.  8.  0.  0.  8. 12.  7.  5.  0. 11.  0. 12. 10.  0.  0. 14.  5.  6.
  8.  8. 10.  0. 15.  8.  7.  

In [178]:
#
# for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
#    This is done through the "StandardScaler" in scikit-learn
#
from sklearn.preprocessing import StandardScaler

USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    scaler = StandardScaler()
    scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
else:
    # this one does no scaling!  We still create it to be consistent:
    scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
    scaler.fit(X_train)  # still need to fit, though it does not change...

scaler   # is now defined and ready to use...

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Here are our scaled training and testing sets:

X_train_scaled = scaler.transform(X_train) # scale!
X_test_scaled = scaler.transform(X_test) # scale!

y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler

# reused from above - seeing the scaled data 
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

# reused from above - seeing the unscaled data (inverting the scaler)
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler)

                                                    input  ->  pred   des  
                                     [0.   1.85 1.63 0.99] ->    ?    8.0                  
                                 [ 0.   -0.34 -0.45  0.05] ->    ?    16.0                 
                                 [ 0.   -0.34 -1.07 -2.53] ->    ?    16.0                 
                                 [ 0.   -0.34  1.21  0.99] ->    ?    0.0                  
                                     [0.   1.85 2.25 0.99] ->    ?    0.0                  

                                                    input  ->  pred   des  
                                         [ 0.  2. 13. 16.] ->    ?    8.0                  
                                         [ 0.  0.  3. 12.] ->    ?    16.0                 
                                             [0. 0. 0. 1.] ->    ?    16.0                 
                                         [ 0.  0. 11. 16.] ->    ?    0.0                  
                   

In [179]:
#
# MLPRegressor predicts _floating-point_ outputs
#

from sklearn.neural_network import MLPRegressor

nn_regressor = MLPRegressor(hidden_layer_sizes=(6,7), 
                    max_iter=500,          # how many training epochs
                    verbose=True,          # do we want to watch as it trains?
                    shuffle=True,          # shuffle each epoch?
                    random_state=None,     # use for reproducibility
                    learning_rate_init=.1, # how much of each error to back-propagate
                    learning_rate = 'adaptive')  # how to handle the learning_rate

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train_scaled, y_train_scaled)
print("++++++++++  TRAINING:   end  +++++++++++++++")
print(f"The (squared) prediction error (the loss) is {nn_regressor.loss_:<6.3f}")
print(f"And, its square root:         {nn_regressor.loss_ ** 0.5:<6.3f}")
print()



++++++++++  TRAINING:  begin  +++++++++++++++


Iteration 1, loss = 19.98938848
Iteration 2, loss = 7.77101264
Iteration 3, loss = 5.01025790
Iteration 4, loss = 4.00862691
Iteration 5, loss = 3.99226371
Iteration 6, loss = 3.74461930
Iteration 7, loss = 3.56523941
Iteration 8, loss = 2.94293311
Iteration 9, loss = 2.90354733
Iteration 10, loss = 2.70836807
Iteration 11, loss = 2.57721370
Iteration 12, loss = 2.37458953
Iteration 13, loss = 2.66159164
Iteration 14, loss = 2.21991250
Iteration 15, loss = 2.37859610
Iteration 16, loss = 2.58561795
Iteration 17, loss = 2.62220466
Iteration 18, loss = 2.26104058
Iteration 19, loss = 2.23500906
Iteration 20, loss = 2.11530651
Iteration 21, loss = 2.16004690
Iteration 22, loss = 1.95401905
Iteration 23, loss = 1.97494215
Iteration 24, loss = 2.06696548
Iteration 25, loss = 2.11909186
Iteration 26, loss = 2.64876619
Iteration 27, loss = 2.38016501
Iteration 28, loss = 1.96672306
Iteration 29, loss = 1.73964616
Iteration 30, loss = 1.9677688

In [ ]:
#
# how did it do? Try out the TEST data...
#

def ascii_table_for_regressor(Xsc,y,nn,scaler):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(Xsc) # all predictions
    Xpr = scaler.inverse_transform(Xsc)  # Xpr is the "X to print": unscaled data!
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>35s} ->  {'pred':^6s}  {'des.':^6s}   {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # Xpr = Xsc   # if you'd like to see the scaled values
        print(f"{Xpr[i,:]!s:>35s} ->  {pred:<+6.2f}  {desired:<+6.2f}   {result:^10.2f}") 

    print("\n" + "+++++   +++++   +++++           ")
    print(f"average abs diff error:   {error/len(y):<6.3f}")
    print("+++++   +++++   +++++           ")
    
#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor,
                          scaler)   # this is our own f'n, above


                             input  ->   pred    des.     absdiff  
[ 0.00e+00  0.00e+00  0.00e+00  1.20e+01  7.00e+00  8.88e-16  0.00e+00
  0.00e+00  0.00e+00  2.22e-16  6.00e+00  1.50e+01  1.00e+00  1.00e+00
  0.00e+00  0.00e+00  0.00e+00  1.00e+00  1.40e+01  8.00e+00  1.00e+01
  8.00e+00  0.00e+00  0.00e+00  0.00e+00  6.00e+00  1.50e+01  0.00e+00
  1.30e+01  1.20e+01  6.00e+00  0.00e+00  0.00e+00  1.40e+01  1.50e+01
  1.20e+01  1.60e+01  1.60e+01  9.00e+00  0.00e+00  0.00e+00  1.00e+01
  1.50e+01  1.60e+01  8.00e+00  1.00e+00  0.00e+00 -8.67e-19  0.00e+00
 -8.88e-16  1.00e+01  1.60e+01  1.00e+00  4.44e-16  0.00e+00  0.00e+00
  0.00e+00  0.00e+00  1.20e+01  9.00e+00  8.88e-16  0.00e+00  0.00e+00
  1.39e-17  0.00e+00 -1.39e-17  0.00e+00  1.00e+00  0.00e+00  0.00e+00
  0.00e+00  0.00e+00  0.00e+00] ->  +20.83  +16.00      4.83   
[ 0.00e+00  0.00e+00  1.00e+00  1.20e+01  8.00e+00  8.88e-16  0.00e+00
  0.00e+00  0.00e+00  2.22e-16  1.10e+01  1.50e+01  5.00e+00  0.00e+00
  0.00e+00  0.00

# Any pixel input

In [196]:
#
# Here we set up for a regression model that will predict 'pix42'  (column index 42)

print("+++ Start of data-assembly for feature-regression! +++\n")

desired_pixel = int(input("What pixel do you want to predict? (0-63)"))
def pixel_predict_regression(i):
    print(f"Predicting pixel {i}!")
    X_all = np.concatenate( (A[:,0:i], A[:,i+1:]), axis=1)    # includes all other columns
    y_all = A[:,i]                    # y (labels) ... pixel we are predicting

    # print(f"y_all is \n {y_all}")
    # print() 
    # print(f"X_all (the features, first few rows) is \n {X_all[:5,:]}")

    #
    indices = np.random.permutation(len(y_all))  # indices is a permutation-list

    # we scramble both X and y, necessarily with the same permutation
    X_all = X_all[indices]              # we apply the _same_ permutation to each!
    y_all = y_all[indices]              # again...
    # print("target values to predict: \n",y_all)
    # print("\nfeatures (a few)\n", X_all[0:5,:])


    #
    # We next separate into test data and training data ... 
    from sklearn.model_selection import train_test_split

    X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

    # print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

    # print(f"Held-out data... (testing data: {len(y_test)})")
    # print(f"y_test: {y_test}\n")
    # print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
    # print()
    # print(f"Data used for modeling... (training data: {len(y_train)})")
    # print(f"y_train: {y_train}\n")
    # print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows


    #
    # for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
    #    This is done through the "StandardScaler" in scikit-learn
    #
    from sklearn.preprocessing import StandardScaler

    USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

    # we "train the scaler"  (computes the mean and standard deviation)
    if USE_SCALER == True:
        scaler = StandardScaler()
        scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
    else:
        # this one does no scaling!  We still create it to be consistent:
        scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
        scaler.fit(X_train)  # still need to fit, though it does not change...

    scaler   # is now defined and ready to use...

    # ++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Here are our scaled training and testing sets:

    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!

    y_train_scaled = y_train  # the predicted/desired labels are not scaled
    y_test_scaled = y_test  # not using the scaler

    # reused from above - seeing the scaled data 
    # ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

    # # reused from above - seeing the unscaled data (inverting the scaler)
    # ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler)


        #
    # MLPRegressor predicts _floating-point_ outputs
    #

    from sklearn.neural_network import MLPRegressor

    nn_regressor = MLPRegressor(hidden_layer_sizes=(6,7), 
                        max_iter=500,          # how many training epochs
                        verbose=False,          # do we want to watch as it trains?
                        shuffle=True,          # shuffle each epoch?
                        random_state=None,     # use for reproducibility
                        learning_rate_init=.1, # how much of each error to back-propagate
                        learning_rate = 'adaptive')  # how to handle the learning_rate

    # print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
    nn_regressor.fit(X_train_scaled, y_train_scaled)
    # print("++++++++++  TRAINING:   end  +++++++++++++++")
    print(f"The (squared) prediction error (the loss) is {nn_regressor.loss_:<6.3f}")
    print(f"And, its square root:         {nn_regressor.loss_ ** 0.5:<6.3f}")
    print()   

    #
    # how did it do? Try out the TEST data...
    #

    def ascii_table_for_regressor(Xsc,y,nn,scaler):
        """ a table including predictions using nn.predict """
        predictions = nn.predict(Xsc) # all predictions
        Xpr = scaler.inverse_transform(Xsc)  # Xpr is the "X to print": unscaled data!
        # measure error
        error = 0.0
        # printing
        # print(f"{'input ':>35s} ->  {'pred':^6s}  {'des.':^6s}   {'absdiff':^10s}") 
        for i in range(len(y)):
            pred = predictions[i]
            desired = y[i]
            result = abs(desired - pred)
            error += result
            # Xpr = Xsc   # if you'd like to see the scaled values
            # print(f"{Xpr[i,:]!s:>35s} ->  {pred:<+6.2f}  {desired:<+6.2f}   {result:^10.2f}") 

        print("+++++   +++++   +++++           ")
        print(f"average abs diff error:   {error/len(y):<6.3f}")
        print("+++++   +++++   +++++           ")
        
    #
    # let's see how it did on the test data (also the training data!)
    #
    ascii_table_for_regressor(X_test_scaled,
                            y_test_scaled,
                            nn_regressor,
                            scaler)   # this is our own f'n, above

pixel_predict_regression(desired_pixel)

+++ Start of data-assembly for feature-regression! +++

Predicting pixel 47!
The (squared) prediction error (the loss) is 0.036 
And, its square root:         0.189 

+++++   +++++   +++++           
average abs diff error:   0.068 
+++++   +++++   +++++           


# All-pixel regression

In [181]:
#
# What shall we predict today?
print(COL_INDEX)
print()
print(COLUMNS)

# We need to predict pixels 0-63, or column indexes 0-63

{'pix0': 0, 'pix1': 1, 'pix2': 2, 'pix3': 3, 'pix4': 4, 'pix5': 5, 'pix6': 6, 'pix7': 7, 'pix8': 8, 'pix9': 9, 'pix10': 10, 'pix11': 11, 'pix12': 12, 'pix13': 13, 'pix14': 14, 'pix15': 15, 'pix16': 16, 'pix17': 17, 'pix18': 18, 'pix19': 19, 'pix20': 20, 'pix21': 21, 'pix22': 22, 'pix23': 23, 'pix24': 24, 'pix25': 25, 'pix26': 26, 'pix27': 27, 'pix28': 28, 'pix29': 29, 'pix30': 30, 'pix31': 31, 'pix32': 32, 'pix33': 33, 'pix34': 34, 'pix35': 35, 'pix36': 36, 'pix37': 37, 'pix38': 38, 'pix39': 39, 'pix40': 40, 'pix41': 41, 'pix42': 42, 'pix43': 43, 'pix44': 44, 'pix45': 45, 'pix46': 46, 'pix47': 47, 'pix48': 48, 'pix49': 49, 'pix50': 50, 'pix51': 51, 'pix52': 52, 'pix53': 53, 'pix54': 54, 'pix55': 55, 'pix56': 56, 'pix57': 57, 'pix58': 58, 'pix59': 59, 'pix60': 60, 'pix61': 61, 'pix62': 62, 'pix63': 63, 'is_0': 64, 'is_1': 65, 'is_2': 66, 'is_3': 67, 'is_4': 68, 'is_5': 69, 'is_6': 70, 'is_7': 71, 'is_8': 72, 'is_9': 73}

Index(['pix0', 'pix1', 'pix2', 'pix3', 'pix4', 'pix5', 'pix6', 'pi

In [191]:
#
# Here we set up for a regression model that will predict 'pix42'  (column index 42)

print("+++ Start of data-assembly for feature-regression! +++\n")
# construct the correct X_all from the columns we want
for i in range(0,63):
    print(f" ")
    print(f" ")
    print(f"Predicting pixel {i}!")
    X_all = np.concatenate( (A[:,0:i], A[:,i+1:]), axis=1)    # includes all other columns
    y_all = A[:,i]                    # y (labels) ... pixel we are predicting

    # print(f"y_all is \n {y_all}")
    # print() 
    # print(f"X_all (the features, first few rows) is \n {X_all[:5,:]}")

    #
    indices = np.random.permutation(len(y_all))  # indices is a permutation-list

    # we scramble both X and y, necessarily with the same permutation
    X_all = X_all[indices]              # we apply the _same_ permutation to each!
    y_all = y_all[indices]              # again...
    # print("target values to predict: \n",y_all)
    # print("\nfeatures (a few)\n", X_all[0:5,:])


    #
    # We next separate into test data and training data ... 
    from sklearn.model_selection import train_test_split

    X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

    # print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

    # print(f"Held-out data... (testing data: {len(y_test)})")
    # print(f"y_test: {y_test}\n")
    # print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
    # print()
    # print(f"Data used for modeling... (training data: {len(y_train)})")
    # print(f"y_train: {y_train}\n")
    # print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows


    #
    # for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
    #    This is done through the "StandardScaler" in scikit-learn
    #
    from sklearn.preprocessing import StandardScaler

    USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

    # we "train the scaler"  (computes the mean and standard deviation)
    if USE_SCALER == True:
        scaler = StandardScaler()
        scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
    else:
        # this one does no scaling!  We still create it to be consistent:
        scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
        scaler.fit(X_train)  # still need to fit, though it does not change...

    scaler   # is now defined and ready to use...

    # ++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Here are our scaled training and testing sets:

    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!

    y_train_scaled = y_train  # the predicted/desired labels are not scaled
    y_test_scaled = y_test  # not using the scaler

    # reused from above - seeing the scaled data 
    # ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

    # # reused from above - seeing the unscaled data (inverting the scaler)
    # ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler)

    
     #
    # MLPRegressor predicts _floating-point_ outputs
    #

    from sklearn.neural_network import MLPRegressor

    nn_regressor = MLPRegressor(hidden_layer_sizes=(6,7), 
                        max_iter=500,          # how many training epochs
                        verbose=False,          # do we want to watch as it trains?
                        shuffle=True,          # shuffle each epoch?
                        random_state=None,     # use for reproducibility
                        learning_rate_init=.1, # how much of each error to back-propagate
                        learning_rate = 'adaptive')  # how to handle the learning_rate

    # print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
    nn_regressor.fit(X_train_scaled, y_train_scaled)
    # print("++++++++++  TRAINING:   end  +++++++++++++++")
    print(f"The (squared) prediction error (the loss) is {nn_regressor.loss_:<6.3f}")
    print(f"And, its square root:         {nn_regressor.loss_ ** 0.5:<6.3f}")
    print()   

    #
    # how did it do? Try out the TEST data...
    #

    def ascii_table_for_regressor(Xsc,y,nn,scaler):
        """ a table including predictions using nn.predict """
        predictions = nn.predict(Xsc) # all predictions
        Xpr = scaler.inverse_transform(Xsc)  # Xpr is the "X to print": unscaled data!
        # measure error
        error = 0.0
        # printing
        # print(f"{'input ':>35s} ->  {'pred':^6s}  {'des.':^6s}   {'absdiff':^10s}") 
        for i in range(len(y)):
            pred = predictions[i]
            desired = y[i]
            result = abs(desired - pred)
            error += result
            # Xpr = Xsc   # if you'd like to see the scaled values
            # print(f"{Xpr[i,:]!s:>35s} ->  {pred:<+6.2f}  {desired:<+6.2f}   {result:^10.2f}") 

        print("+++++   +++++   +++++           ")
        print(f"average abs diff error:   {error/len(y):<6.3f}")
        print("+++++   +++++   +++++           ")
        
    #
    # let's see how it did on the test data (also the training data!)
    #
    ascii_table_for_regressor(X_test_scaled,
                            y_test_scaled,
                            nn_regressor,
                            scaler)   # this is our own f'n, above

    

+++ Start of data-assembly for feature-regression! +++

 
 
Predicting pixel 0!
The (squared) prediction error (the loss) is 0.000 
And, its square root:         0.005 

+++++   +++++   +++++           
average abs diff error:   0.001 
+++++   +++++   +++++           
 
 
Predicting pixel 1!
The (squared) prediction error (the loss) is 0.049 
And, its square root:         0.222 

+++++   +++++   +++++           
average abs diff error:   0.182 
+++++   +++++   +++++           
 
 
Predicting pixel 2!
The (squared) prediction error (the loss) is 0.760 
And, its square root:         0.872 

+++++   +++++   +++++           
average abs diff error:   1.118 
+++++   +++++   +++++           
 
 
Predicting pixel 3!
The (squared) prediction error (the loss) is 1.325 
And, its square root:         1.151 

+++++   +++++   +++++           
average abs diff error:   1.643 
+++++   +++++   +++++           
 
 
Predicting pixel 4!
The (squared) prediction error (the loss) is 2.292 
And, its square 

# saving the chart & questions of this section for HW8...!