<br>

###   <font color="Coral">hw7pr2digits_modeler</font>
+ digits clasification -- and regression -- via NNets

Feel free to re-use your previous digits_cleaned.csv file 


### First, use the iris example to create a digit-predicting NNet

This is similar to the past two digits challenges, hw5 and hw6

**However**, because we're using NNets, you'll need to
+ create TEN categorical variables. You can use just one ``get_dummies`` pandas call
+ use a SCALER to make sure the network can, in a fair way, "hear" all of the inputs 

In [1]:
#
# coding cell to make sure Python is happy...

14*3

42

In [1]:
# libraries...
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

#### Reading the data

In [2]:
filename = 'digits_cleaned.csv' # neighborhoods
df_tidy = pd.read_csv(filename)      # encoding = "utf-8", "latin1"
print(f"{filename} : file read into a pandas dataframe.")

digits_cleaned.csv : file read into a pandas dataframe.


In [3]:
print(f"df_tidy.shape is {df_tidy.shape}\n")
df_tidy.info()  # prints column information
df_tidy

df_tidy.shape is (1768, 66)

<class 'pandas.core.frame.DataFrame'>
Index: 1768 entries, 0 to 1767
Data columns (total 66 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   pix0          1768 non-null   int64
 1   pix1          1768 non-null   int64
 2   pix2          1768 non-null   int64
 3   pix3          1768 non-null   int64
 4   pix4          1768 non-null   int64
 5   pix5          1768 non-null   int64
 6   pix6          1768 non-null   int64
 7   pix7          1768 non-null   int64
 8   pix8          1768 non-null   int64
 9   pix9          1768 non-null   int64
 10  pix10         1768 non-null   int64
 11  pix11         1768 non-null   int64
 12  pix12         1768 non-null   int64
 13  pix13         1768 non-null   int64
 14  pix14         1768 non-null   int64
 15  pix15         1768 non-null   int64
 16  pix16         1768 non-null   int64
 17  pix17         1768 non-null   int64
 18  pix18         1768 non-null   int64
 19  pix

pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...  pix56  \
0        0     0     9    14     8     1     0     0     0     0  ...      0   
1        0     0    11    12     0     0     0     0     0     2  ...      0   
2        0     0     1     9    15    11     0     0     0     0  ...      0   
3        0     0     0     0    14    13     1     0     0     0  ...      0   
4        0     0     5    12     1     0     0     0     0     0  ...      0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...      0   
1764     0     0     6    16    13    11     1     0     0     0  ...      0   
1765     0     0     1    11    15     1     0     0     0     0  ...      0   
1766     0     0     2    10     7     0     0     0     0     0  ...      0   
1767     0     0    10    14     8     1     0     0     0     2  ...      0   

      pix57  pix58  pix59  pix60  pix61  pix62  pix63  actual_digit  numbernum  
0         0     11     16     15     11      1      0             8          8  
1         0      9     12     13      3      0      0             9          9  
2         0      1     10     13      3      0      0             0          0  
3         0      0      1     13     16      1      0             1          1  
4         0      3     11      8     13     12      4             2          2  
...     ...    ...    ...    ...    ...    ...    ...           ...        ...  
1763      0      2     14     15      9      0      0             9          9  
1764      0      6     16     14      6      0      0             0          0  
1765      0      2      9     13      6      0      0             8          8  
1766      0      5     12     16     12      0      0             9          9  
1767      1      8     12     14     12      1      0             8          8  

[1768 rows x 66 columns]

In [4]:
df_tidy_cat = pd.get_dummies(data=df_tidy,prefix="is",columns=['actual_digit'])
df_tidy_cat

pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...   is_0  \
0        0     0     9    14     8     1     0     0     0     0  ...  False   
1        0     0    11    12     0     0     0     0     0     2  ...  False   
2        0     0     1     9    15    11     0     0     0     0  ...   True   
3        0     0     0     0    14    13     1     0     0     0  ...  False   
4        0     0     5    12     1     0     0     0     0     0  ...  False   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...  False   
1764     0     0     6    16    13    11     1     0     0     0  ...   True   
1765     0     0     1    11    15     1     0     0     0     0  ...  False   
1766     0     0     2    10     7     0     0     0     0     0  ...  False   
1767     0     0    10    14     8     1     0     0     0     2  ...  False   

       is_1   is_2   is_3   is_4   is_5   is_6   is_7   is_8   is_9  
0     False  False  False  False  False  False  False   True  False  
1     False  False  False  False  False  False  False  False   True  
2     False  False  False  False  False  False  False  False  False  
3      True  False  False  False  False  False  False  False  False  
4     False   True  False  False  False  False  False  False  False  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...  
1763  False  False  False  False  False  False  False  False   True  
1764  False  False  False  False  False  False  False  False  False  
1765  False  False  False  False  False  False  False   True  False  
1766  False  False  False  False  False  False  False  False   True  
1767  False  False  False  False  False  False  False   True  False  

[1768 rows x 75 columns]

In [5]:
ROW = 0
COLUMN = 1
df_model1 = df_tidy_cat.drop('numbernum', axis=COLUMN )
df_model1

pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...   is_0  \
0        0     0     9    14     8     1     0     0     0     0  ...  False   
1        0     0    11    12     0     0     0     0     0     2  ...  False   
2        0     0     1     9    15    11     0     0     0     0  ...   True   
3        0     0     0     0    14    13     1     0     0     0  ...  False   
4        0     0     5    12     1     0     0     0     0     0  ...  False   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...  False   
1764     0     0     6    16    13    11     1     0     0     0  ...   True   
1765     0     0     1    11    15     1     0     0     0     0  ...  False   
1766     0     0     2    10     7     0     0     0     0     0  ...  False   
1767     0     0    10    14     8     1     0     0     0     2  ...  False   

       is_1   is_2   is_3   is_4   is_5   is_6   is_7   is_8   is_9  
0     False  False  False  False  False  False  False   True  False  
1     False  False  False  False  False  False  False  False   True  
2     False  False  False  False  False  False  False  False  False  
3      True  False  False  False  False  False  False  False  False  
4     False   True  False  False  False  False  False  False  False  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...  
1763  False  False  False  False  False  False  False  False   True  
1764  False  False  False  False  False  False  False  False  False  
1765  False  False  False  False  False  False  False   True  False  
1766  False  False  False  False  False  False  False  False   True  
1767  False  False  False  False  False  False  False   True  False  

[1768 rows x 74 columns]

In [6]:
#
# once we have all the columns we want, let's create an index of their names...

#
# Let's make sure we have all of our helpful variables in one place 
#       To be adapted if we drop/add more columns...
#

#
# let's keep our column names in variables, for reference
#
COLUMNS = df_model1.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
  # It's a "pandas" list, called an Index
  # use it just as a Python list of strings:
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}\n\n")


#
# and our "species" names
#

# all of scikit-learn's ML routines need numbers, not strings
#   ... even for categories/classifications (like species!)
#   so, we will convert the flower-species to numbers:

DIGITS = ['0','1','2','3','4','5','6','7','8','9']   # int to str
DIGITS_INDEX = {'0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9}  # str to int

# Let's try it out...
for name in DIGITS:
    print(f"{name} maps to {DIGITS_INDEX[name]}")

COLUMNS is Index(['pix0', 'pix1', 'pix2', 'pix3', 'pix4', 'pix5', 'pix6', 'pix7', 'pix8',
       'pix9', 'pix10', 'pix11', 'pix12', 'pix13', 'pix14', 'pix15', 'pix16',
       'pix17', 'pix18', 'pix19', 'pix20', 'pix21', 'pix22', 'pix23', 'pix24',
       'pix25', 'pix26', 'pix27', 'pix28', 'pix29', 'pix30', 'pix31', 'pix32',
       'pix33', 'pix34', 'pix35', 'pix36', 'pix37', 'pix38', 'pix39', 'pix40',
       'pix41', 'pix42', 'pix43', 'pix44', 'pix45', 'pix46', 'pix47', 'pix48',
       'pix49', 'pix50', 'pix51', 'pix52', 'pix53', 'pix54', 'pix55', 'pix56',
       'pix57', 'pix58', 'pix59', 'pix60', 'pix61', 'pix62', 'pix63', 'is_0',
       'is_1', 'is_2', 'is_3', 'is_4', 'is_5', 'is_6', 'is_7', 'is_8', 'is_9'],
      dtype='object')

COLUMNS[0] is pix0

COL_INDEX is {'pix0': 0, 'pix1': 1, 'pix2': 2, 'pix3': 3, 'pix4': 4, 'pix5': 5, 'pix6': 6, 'pix7': 7, 'pix8': 8, 'pix9': 9, 'pix10': 10, 'pix11': 11, 'pix12': 12, 'pix13': 13, 'pix14': 14, 'pix15': 15, 'pix16': 16, 'pix17': 17, 'pix18':

In [7]:
A = df_model1.to_numpy()   
A = A.astype('float64')    # many types:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A[:,:])

[[ 0.  0.  9. ...  0.  1.  0.]
 [ 0.  0. 11. ...  0.  0.  1.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  1. ...  0.  1.  0.]
 [ 0.  0.  2. ...  0.  0.  1.]
 [ 0.  0. 10. ...  0.  1.  0.]]


In [8]:
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 1768 rows and 74 cols


#### We have full access to individual data elements

In [9]:
# let's use all of our variables, to reinforce that we have
# (1) names...
# (2) access and control...

# choose a row index, n:
n = 42
print(f"Digit #{n} is {A[n]}")
digits = ""

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    value = A[n][i]
    print(f"  Its {colname} is {value}")
    if "0" in colname: digits = "0"
    elif "1" in colname: digits = "1"
    elif "2" in colname: digits = "2"
    elif "3" in colname: digits = "3"
    elif "4" in colname: digits = "4"
    elif "5" in colname: digits = "5"
    elif "6" in colname: digits = "6"
    elif "7" in colname: digits = "7"
    elif "8" in colname: digits = "8"
    elif "9" in colname: digits = "9"

print()
print(f"  and its digit name: {digits}")

Digit #42 is [ 0.  0.  0. 10. 11.  0.  0.  0.  0.  0.  9. 16.  6.  0.  0.  0.  0.  0.
 15. 13.  0.  0.  0.  0.  0.  0. 14. 10.  0.  0.  0.  0.  0.  1. 15. 12.
  8.  2.  0.  0.  0.  0. 12. 16. 16. 16. 10.  1.  0.  0.  7. 16. 12. 12.
 16.  4.  0.  0.  0.  9. 15. 12.  5.  0.  0.  0.  0.  0.  0.  0.  1.  0.
  0.  0.]
  Its pix0 is 0.0
  Its pix1 is 0.0
  Its pix2 is 0.0
  Its pix3 is 10.0
  Its pix4 is 11.0
  Its pix5 is 0.0
  Its pix6 is 0.0
  Its pix7 is 0.0
  Its pix8 is 0.0
  Its pix9 is 0.0
  Its pix10 is 9.0
  Its pix11 is 16.0
  Its pix12 is 6.0
  Its pix13 is 0.0
  Its pix14 is 0.0
  Its pix15 is 0.0
  Its pix16 is 0.0
  Its pix17 is 0.0
  Its pix18 is 15.0
  Its pix19 is 13.0
  Its pix20 is 0.0
  Its pix21 is 0.0
  Its pix22 is 0.0
  Its pix23 is 0.0
  Its pix24 is 0.0
  Its pix25 is 0.0
  Its pix26 is 14.0
  Its pix27 is 10.0
  Its pix28 is 0.0
  Its pix29 is 0.0
  Its pix30 is 0.0
  Its pix31 is 0.0
  Its pix32 is 0.0
  Its pix33 is 1.0
  Its pix34 is 15.0
  Its pix35 is 12.0
  

### Defining X_all (our features) and y_all (our target to predict) 

In [10]:
print("+++ Start of data definitions +++\n")

#
# we could do this at the data-frame level, too!
#

X_all = A[:,0:64]   # X (features) ... is all rows, columns 0, 1, 2, 3
y_all = A[:,64:]    # y (labels) ... is all rows, columns 4, 5, and 6

print(f"y_all (just the labels/species, first few rows) are \n {y_all[0:5]}")
print()
print(f"X_all (just the features, first few rows) are \n {X_all[0:5]}")

+++ Start of data definitions +++

y_all (just the labels/species, first few rows) are 
 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]

X_all (just the features, first few rows) are 
 [[ 0.  0.  9. 14.  8.  1.  0.  0.  0.  0. 12. 14. 14. 12.  0.  0.  0.  0.
   9. 10.  0. 15.  4.  0.  0.  0.  3. 16. 12. 14.  2.  0.  0.  0.  4. 16.
  16.  2.  0.  0.  0.  3. 16.  8. 10. 13.  2.  0.  0.  1. 15.  1.  3. 16.
   8.  0.  0.  0. 11. 16. 15. 11.  1.  0.]
 [ 0.  0. 11. 12.  0.  0.  0.  0.  0.  2. 16. 16. 16. 13.  0.  0.  0.  3.
  16. 12. 10. 14.  0.  0.  0.  1. 16.  1. 12. 15.  0.  0.  0.  0. 13. 16.
   9. 15.  2.  0.  0.  0.  0.  3.  0.  9. 11.  0.  0.  0.  0.  0.  9. 15.
   4.  0.  0.  0.  9. 12. 13.  3.  0.  0.]
 [ 0.  0.  1.  9. 15. 11.  0.  0.  0.  0. 11. 16.  8. 14.  6.  0.  0.  2.
  16. 10.  0.  9.  9.  0.  0.  1. 16.  4.  0.  8.  8.  0.  0.  4. 16.  4.
   0.  8.  8.  0. 

### Permute...

In [11]:
#
# we can scramble the data, to remove (potential) dependence on its ordering: 
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print(f"The scrambled labels/species are \n {y_all[0:5]}")
print()
print(f"The corresponding data rows are \n {X_all[0:5]}")

The scrambled labels/species are 
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

The corresponding data rows are 
 [[ 0.  0.  5. 16. 16.  3.  0.  0.  0.  0.  9. 16.  7.  0.  0.  0.  0.  0.
  12. 15.  2.  0.  0.  0.  0.  1. 15. 16. 15.  4.  0.  0.  0.  0.  9. 13.
  16.  9.  0.  0.  0.  0.  0.  0. 14. 12.  0.  0.  0.  0.  5. 12. 16.  8.
   0.  0.  0.  0.  3. 15. 15.  1.  0.  0.]
 [ 0.  0.  1. 12. 10.  3.  0.  0.  0.  0.  7. 16. 16.  7.  0.  0.  0.  0.
  12. 16. 16.  3.  0.  0.  0.  0. 14. 16. 16.  2.  0.  0.  0.  1. 15. 16.
  16.  5.  0.  0.  0.  0. 15. 16. 15.  2.  0.  0.  0.  0. 11. 16. 16.  8.
   0.  0.  0.  0.  1.  7. 12. 10.  0.  0.]
 [ 0.  0.  0.  9. 13. 10.  1.  0.  0.  0.  9. 12.  4. 15.  5.  0.  0.  0.
  16.  4.  0. 12.  4.  0.  0.  3. 15.  9.  3. 14.  1.  0.  0.  0.  2.  9.
  16. 10.  0.  0.  0.  0.  0.  4. 14. 15.  2.  0.  0.  0.  0. 10.  8. 14.
   3.  0.  0

### Separate into training and testing
+ X_train, y_train will be used for model-building
+ X_test, y_test will be used for testing, later

In [12]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"+++ Testing +++   Held-out data... (testing data: {len(y_test)})\n")
print(f"y_test: {y_test[0:5,:]}\n")
print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
print("\n")
print(f"+++ Training +++   Data used for modeling... (training data: {len(y_train)})\n")
print(f"y_train: {y_train[0:5,:]}\n")
print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows

training with 1414 rows;  testing with 354 rows

+++ Testing +++   Held-out data... (testing data: 354)

y_test: [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

X_test (few rows): [[ 0.  0.  7. 15. 15.  5.  0.  0.  0.  6. 16. 12. 16. 12.  0.  0.  0.  1.
   7.  0. 16. 10.  0.  0.  0.  0.  0. 10. 15.  0.  0.  0.  0.  0.  1. 16.
   7.  0.  0.  0.  0.  0. 10. 13.  1.  5.  1.  0.  0.  0. 12. 12. 13. 15.
   3.  0.  0.  0. 10. 16. 13.  3.  0.  0.]
 [ 0.  0. 15. 16. 12.  5.  0.  0.  0.  1. 16. 15. 11.  7.  0.  0.  0.  4.
  16.  9.  0.  0.  0.  0.  0.  8. 16. 14. 12.  7.  0.  0.  0.  7. 16. 14.
  10. 16.  3.  0.  0.  0.  1.  0. 10. 16.  4.  0.  0.  0.  1. 10. 16. 10.
   0.  0.  0.  0. 13. 15.  5.  0.  0.  0.]
 [ 0.  0.  0.  9. 16.  9.  0.  0.  0.  0.  3. 15.  5. 16.  0.  0.  0.  0.
   7. 12.  7. 12.  0.  0.  0.  0.  1. 16. 16.  5.  0.  0.  0.  0.  2. 16.
  14.  1.  0.  0.  0.  

### NNets often need a ***Scaler***

This scales all of the data so that it's of a similar size, e.g., -1 to 1

Notice that this cell produces
+ X_train_scaled &nbsp; (the scaled training data)
   + y_train_scaled is the same as y_train &nbsp; (no scaling needed for the target)
+ X_test_scaled &nbsp; (the scaled testing data)
   + y_test_scaled is the same as y_test &nbsp; (no scaling needed for the target)

After this, we just use the scaled data...

In [13]:
#
# for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
#    This is done through the "StandardScaler" in scikit-learn
# 
from sklearn.preprocessing import StandardScaler

#
# do we want to use a Scaler?
#
USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    scaler = StandardScaler()
    scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
else:
    # this one does no scaling!  We still create it to be consistent:
    scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
    scaler.fit(X_train)  # still need to fit, though it does not change...

scaler   # is now defined and ready to use...

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Here are our scaled training and testing sets:

X_train_scaled = scaler.transform(X_train) # scale!
X_test_scaled = scaler.transform(X_test) # scale!

y_train_scaled = y_train.copy()  # the predicted/desired labels are not scaled
y_test_scaled = y_test.copy()  # not using the scaler



### Intuition-building for the Scaled data

In [14]:
#
# let's create a table for showing our data and its predictions...
#
def ascii_table(X,y,scaler_to_invert=None):
    """ print a table of inputs and outputs """
    np.set_printoptions(precision=2)  # Let's use less precision
    if scaler_to_invert == None:  # don't use the scaler
        X = X
    else:
        X = scaler_to_invert.inverse_transform(X)
    print(f"{'input ':>58s} -> {'pred':^7s} {'des':<5s}") 
    for i in range(len(y)):
        # whoa! serious f-string formatting:
        print(f"{str(X[i,0:64]):>58s} -> {'?':^7s} {str(y[i]):<21s}")   # !s is str ...
    print()
    
# to show the table with the scaled data:
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

# to show the table with the original data:
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler_to_invert=scaler)

                                                    input  ->  pred   des  
[ 0.   -0.34 -0.87 -0.42  0.75  0.93  1.71 -0.13 -0.07 -0.62 -0.97  1.01
  1.18  1.3   2.55 -0.13 -0.04 -0.72 -0.69  1.55  1.43  1.32  1.29 -0.11
  0.   -0.78  0.47  1.21  0.98  0.75 -0.63 -0.05  0.   -0.1   1.32  1.09
  0.96 -0.45 -0.81  0.   -0.06  0.14  0.78  1.35  0.69 -1.43 -0.8  -0.09
 -0.03 -0.41  0.27  1.23  1.26 -0.3  -0.76 -0.2  -0.03 -0.3  -0.49 -0.01
  0.83 -0.83 -0.51 -0.18] ->    ?    [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.   -0.34 -1.08 -0.88  0.98  1.83  4.42  5.11 -0.07 -0.62 -0.79  0.51
 -1.1  -0.02  3.94  2.14 -0.04 -0.72 -0.51 -0.52 -1.15 -0.28  3.12 -0.11
  0.   -0.78 -1.48 -1.53 -1.62  0.75  1.01 -0.05  0.   -0.67 -1.21  0.28
  0.96  1.24  2.01  0.   -0.06 -0.53 -1.05  0.73  1.33 -0.03 -0.8  -0.09
 -0.03 -0.41 -1.33 -0.66  1.26 -1.46 -0.76 -0.2  -0.03 -0.3  -1.08 -0.01
 -0.59 -1.16 -0.51 -0.18] ->    ?    [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[ 0.    3.2   2.08  0.75 -2.31 -1.03 -0.41 -0.13 -0.07  

### Training ML models is no problem

that is, if the library does it for us! &nbsp;&nbsp; 😃 🧶 ⛄️ 🌊 🪺 🦔 :-)

In [34]:
from sklearn.neural_network import MLPClassifier

#
# Here's where you can change the number of hidden layers
# and number of neurons!  It's in the tuple  hidden_layer_sizes:
#
nn_classifier = MLPClassifier(hidden_layer_sizes=(6,7),  
                    # hidden_layer_sizes=(6,7)   means   4 inputs -> 6 hidden -> 7 hidden -> 3 outputs
                    max_iter=500,      # how many times to train
                    # activation="tanh", # the "activation function" input -> output
                    # solver='sgd',      # the algorithm for optimizing weights
                    verbose=True,      # False to "mute" the training
                    shuffle=True,      # reshuffle the training epochs?
                    random_state=None, # set for reproduceability
                    learning_rate_init=.1,       # learning rate: the amt of error to backpropagate!
                    learning_rate = 'adaptive')  # soften feedback as it converges

# documentation:
# scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html 
#     Try other network sizes / other parameters ...

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_classifier.fit(X_train_scaled, y_train_scaled)
print("\n++++++++++  TRAINING:   end  +++++++++++++++")
print(f"The analog prediction error (the loss) is {nn_classifier.loss_}")



++++++++++  TRAINING:  begin  +++++++++++++++


Iteration 1, loss = 4.11241560
Iteration 2, loss = 2.10095478
Iteration 3, loss = 1.41103213
Iteration 4, loss = 1.12262708
Iteration 5, loss = 0.95425098
Iteration 6, loss = 0.85533541
Iteration 7, loss = 0.66848366
Iteration 8, loss = 0.56541184
Iteration 9, loss = 0.65143473
Iteration 10, loss = 0.68393095
Iteration 11, loss = 0.57028551
Iteration 12, loss = 0.43211332
Iteration 13, loss = 0.42582807
Iteration 14, loss = 0.53221443
Iteration 15, loss = 0.54675337
Iteration 16, loss = 0.42011650
Iteration 17, loss = 0.44165298
Iteration 18, loss = 0.42384645
Iteration 19, loss = 0.52106243
Iteration 20, loss = 0.62162350
Iteration 21, loss = 0.51236301
Iteration 22, loss = 0.40170395
Iteration 23, loss = 0.42329788
Iteration 24, loss = 0.46766422
Iteration 25, loss = 0.48323522
Iteration 26, loss = 0.48974467
Iteration 27, loss = 0.37621555
Iteration 28, loss = 0.36712233
Iteration 29, loss = 0.33631002
Iteration 30, loss = 0.38619465

### Now, let's test!

In [18]:
L=  [9.74e-22, 2.96e-06, 4.22e-17, 1.63e-03, 1.71e-05, 8.42e-04, 3.41e-20, 2.58e-01,
 9.60e-04, 1.81e-04]
get_digits(L)

'7'

In [17]:
#
# how did it do on the testing data?
#

def get_digits(A):
    m = max(A)
    for i in range(len(A)):
        if A[i] == m: 
            return DIGITS[i]  # note that this "takes the first one"
    return "no digits" 

SEE_PROBS = False

def ascii_table_for_classifier(Xsc,y,nn,scaler):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(Xsc)            # all predictions
    prediction_probs = nn.predict_proba(Xsc) # all prediction probabilities
    Xpr = scaler.inverse_transform(Xsc)      # Xpr is the "X to print": the unscaled data
    # count correct
    num_correct = 0
    # printing
    print(f"{'input ':>28s} -> {'pred':^12s} {'des.':^12s}") 
    for i in range(len(y)):
        pred = predictions[i]
        pred_probs = prediction_probs[i,:]
        desired = y[i].astype(int)
        # print(pred, desired, pred_probs)
        pred_digits = get_digits(pred_probs)
        des_digits  = get_digits(desired)
        if pred_digits != des_digits: result = "  incorrect: " + str(pred_probs)
        else: result = "  correct" + (": "+pred_probs if SEE_PROBS else "") ; num_correct += 1
        # Xpr = Xsc  # if you want to see the scaled versions
        print(f"{Xpr[i,0:65]!s:>28s} -> {pred_digits:^12s} {des_digits:12s} {result:^10s}") 
    print(f"\ncorrect predictions: {num_correct} out of {len(y)}")
    
#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_classifier(X_test_scaled,
                           y_test_scaled,
                           nn_classifier,
                           scaler)   


                      input  ->     pred         des.    
[ 0.00e+00  0.00e+00  7.00e+00  1.50e+01  1.50e+01  5.00e+00  0.00e+00
  0.00e+00  0.00e+00  6.00e+00  1.60e+01  1.20e+01  1.60e+01  1.20e+01
 -2.22e-16 -1.39e-17  0.00e+00  1.00e+00  7.00e+00  8.88e-16  1.60e+01
  1.00e+01 -2.22e-16  0.00e+00  0.00e+00  0.00e+00  0.00e+00  1.00e+01
  1.50e+01  8.88e-16  0.00e+00  0.00e+00  0.00e+00  0.00e+00  1.00e+00
  1.60e+01  7.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  2.22e-16
  1.00e+01  1.30e+01  1.00e+00  5.00e+00  1.00e+00  0.00e+00  0.00e+00
  0.00e+00  1.20e+01  1.20e+01  1.30e+01  1.50e+01  3.00e+00  0.00e+00
  0.00e+00  0.00e+00  1.00e+01  1.60e+01  1.30e+01  3.00e+00  0.00e+00
  0.00e+00] ->      2       2              correct 
[ 0.00e+00  0.00e+00  1.50e+01  1.60e+01  1.20e+01  5.00e+00  0.00e+00
  0.00e+00  0.00e+00  1.00e+00  1.60e+01  1.50e+01  1.10e+01  7.00e+00
 -2.22e-16 -1.39e-17  0.00e+00  4.00e+00  1.60e+01  9.00e+00  0.00e+00
 -8.88e-16 -2.22e-16  0.00e+00  0.00e+

### Let's see the network's weights...

In [19]:
#
# We don't usually look inside the NNet, but we can: it's open-box modeling...
#
if True:  # do we want to see all of the parameters?
    np.set_printoptions(precision=2)  # Let's use less precision
    nn = nn_classifier  # less to type?
    print("\n\n+++++ parameters, weights, etc. +++++\n")
    print(f"\nweights/coefficients:\n")
    for i, wts in enumerate(nn.coefs_):
        print(f"[[ Layer {i} ]]\n   has shape = {wts.shape} and weights =\n{wts}")
        print(f"   with intercepts:\n {nn.intercepts_[i]}\n")
    print()
    print(f"\nall parameters: {nn.get_params()}")



+++++ parameters, weights, etc. +++++


weights/coefficients:

[[ Layer 0 ]]
   has shape = (64, 6) and weights =
[[-5.06e-02  2.11e-04 -1.86e-02 -4.57e-05  2.07e-06  6.58e-03]
 [-8.77e-02 -5.58e-01 -2.12e-01  4.55e-02 -4.82e-01 -7.82e-03]
 [-1.15e+00 -2.41e+00 -2.34e-01 -1.28e+00 -7.02e-02 -1.94e-01]
 [ 1.63e+00 -1.83e+00 -1.53e-01 -4.70e-01 -2.80e-01  1.06e+00]
 [ 1.64e+00  2.68e-01 -2.05e+00 -3.28e-01 -5.14e-01 -7.10e-01]
 [-1.66e+00 -2.86e+00 -9.40e-01 -4.81e+00  6.82e-01 -7.19e-01]
 [ 3.58e-01 -3.85e+00 -1.26e+00 -2.21e+00 -1.35e+00  8.03e-01]
 [ 1.70e-01  1.50e-01 -1.32e+00 -8.58e-01 -1.26e+00  6.33e-01]
 [-6.27e-01 -1.76e-01  4.41e-02 -1.40e+00 -3.08e-01 -1.68e-01]
 [ 1.77e-01 -7.62e-01 -1.72e-01 -4.88e-02  1.19e+00  1.48e+00]
 [-2.40e-01 -1.84e+00  4.68e-01 -3.50e+00 -1.62e+00  1.09e+00]
 [ 5.55e-01 -2.52e-01  4.60e-02 -8.10e-02 -1.03e+00  1.80e-01]
 [ 1.02e+00 -3.53e+00 -2.70e+00  1.88e-01 -1.33e-01  2.72e+00]
 [-4.17e-01 -2.82e+00 -7.29e-02 -1.40e-01 -3.09e-01 -1.47e+00]
 [

In [20]:
for sublist in X_test:
    print(' '.join(str(item) for item in sublist))


0.0 0.0 7.0 15.0 15.0 5.0 0.0 0.0 0.0 6.0 16.0 12.0 16.0 12.0 0.0 0.0 0.0 1.0 7.0 0.0 16.0 10.0 0.0 0.0 0.0 0.0 0.0 10.0 15.0 0.0 0.0 0.0 0.0 0.0 1.0 16.0 7.0 0.0 0.0 0.0 0.0 0.0 10.0 13.0 1.0 5.0 1.0 0.0 0.0 0.0 12.0 12.0 13.0 15.0 3.0 0.0 0.0 0.0 10.0 16.0 13.0 3.0 0.0 0.0
0.0 0.0 15.0 16.0 12.0 5.0 0.0 0.0 0.0 1.0 16.0 15.0 11.0 7.0 0.0 0.0 0.0 4.0 16.0 9.0 0.0 0.0 0.0 0.0 0.0 8.0 16.0 14.0 12.0 7.0 0.0 0.0 0.0 7.0 16.0 14.0 10.0 16.0 3.0 0.0 0.0 0.0 1.0 0.0 10.0 16.0 4.0 0.0 0.0 0.0 1.0 10.0 16.0 10.0 0.0 0.0 0.0 0.0 13.0 15.0 5.0 0.0 0.0 0.0
0.0 0.0 0.0 9.0 16.0 9.0 0.0 0.0 0.0 0.0 3.0 15.0 5.0 16.0 0.0 0.0 0.0 0.0 7.0 12.0 7.0 12.0 0.0 0.0 0.0 0.0 1.0 16.0 16.0 5.0 0.0 0.0 0.0 0.0 2.0 16.0 14.0 1.0 0.0 0.0 0.0 3.0 16.0 8.0 9.0 11.0 0.0 0.0 0.0 0.0 12.0 13.0 4.0 12.0 8.0 0.0 0.0 0.0 0.0 8.0 14.0 16.0 14.0 0.0
0.0 0.0 0.0 6.0 14.0 3.0 0.0 0.0 0.0 0.0 2.0 16.0 11.0 0.0 0.0 0.0 0.0 0.0 11.0 15.0 2.0 0.0 0.0 0.0 0.0 1.0 15.0 13.0 2.0 0.0 0.0 0.0 0.0 3.0 16.0 16.0 16.0 7.0 0.0 0.0 0.0 

### The predictive model

In [27]:
int(np.argmax([0,0,0,0,.0001,0,0,0,0]))

4

In [31]:
#
# final predictive model (random forests), with tuned parameters + ALL data incorporated
#

def get_species(A):
    """ returns the species for A ~ [1 0 0] or [0 1 0] or ... """
    for i in range(len(DIGITS)):
        if A[i] == 1: 
            return DIGITS[i]  # note that this "takes the first one"
    return "no species in get_species" 


def predictive_model( Features, MODEL, SCALER ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    scaled_features = SCALER.transform(our_features)      # we have to scale the features into "scaled space"
    predicted_cat = MODEL.predict(scaled_features)        # then, the nnet can predict our "cat" variables
    prediction_probs = MODEL.predict_proba(scaled_features) # all prediction probabilities
    # our_features = SCALER.inverse_transform(scaled_features)  # we can convert back (optional!)
    #print(predicted_cat[0])
    x = int(np.argmax(prediction_probs))
    #predicted_species = get_species(predicted_cat[0])     # (it's extra-nested) get the species name
    predicted_species = str(x)
    return predicted_species, prediction_probs
   
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [6.7,3.3,5.7,0.1]  # [5.8,2.7,4.1,1.0] [4.6,3.6,3.0,2.2] [6.7,3.3,5.7,2.1]

LoF = [
[0.0, 0.0, 7.0, 13.0, 11.0, 1.0, 0.0, 0.0, 0.0, 6.0, 14.0, 12.0, 14.0, 9.0, 0.0, 0.0, 0.0, 5.0, 14.0, 3.0, 10.0, 9.0, 0.0, 0.0, 0.0, 0.0, 8.0, 15.0, 14.0, 2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 14.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 9.0, 9.0, 3.0, 15.0, 4.0, 0.0, 0.0, 0.0, 12.0, 5.0, 1.0, 11.0, 8.0, 0.0, 0.0, 0.0, 7.0, 16.0, 16.0, 9.0, 1.0, 0.0],   
[0.0, 0.0, 3.0, 13.0, 16.0, 7.0, 0.0, 0.0, 0.0, 1.0, 12.0, 16.0, 8.0, 0.0, 0.0, 0.0, 0.0, 2.0, 16.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 16.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.0, 16.0, 10.0, 11.0, 4.0, 0.0, 0.0, 0.0, 6.0, 16.0, 14.0, 13.0, 16.0, 3.0, 0.0, 0.0, 1.0, 11.0, 11.0, 2.0, 14.0, 10.0, 0.0, 0.0, 0.0, 2.0, 15.0, 16.0, 15.0, 6.0, 0.0],   
[0.0, 0.0, 4.0, 15.0, 16.0, 16.0, 16.0, 1.0, 0.0, 0.0, 10.0, 13.0, 8.0, 15.0, 8.0, 0.0, 0.0, 0.0, 14.0, 5.0, 3.0, 16.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 12.0, 11.0, 0.0, 0.0, 0.0, 0.0, 2.0, 5.0, 16.0, 9.0, 1.0, 0.0, 0.0, 0.0, 15.0, 16.0, 16.0, 14.0, 3.0, 0.0, 0.0, 0.0, 1.0, 15.0, 9.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 14.0, 2.0, 0.0, 0.0, 0.0],   # actually virginica
[0.0, 0.0, 0.0, 1.0, 7.0, 14.0, 14.0, 0.0, 0.0, 0.0, 3.0, 15.0, 7.0, 1.0, 14.0, 0.0, 0.0, 2.0, 16.0, 10.0, 5.0, 14.0, 8.0, 0.0, 0.0, 4.0, 15.0, 16.0, 12.0, 16.0, 5.0, 0.0, 0.0, 0.0, 5.0, 3.0, 1.0, 15.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 12.0, 0.0, 0.0]
]

SEE_PROBS = True

# run on each one:
for Features in LoF:
    MODEL = nn_classifier
    SCALER = scaler
    name, probs = predictive_model( Features, MODEL, SCALER )  # pass in the model, too!
    prob_str = "   with probs: " + str(probs) if SEE_PROBS == True else ""
    print(f"I predict {name:>12s} from the features {Features}  {prob_str}")    # Answers in the assignment...

I predict            8 from the features [0.0, 0.0, 7.0, 13.0, 11.0, 1.0, 0.0, 0.0, 0.0, 6.0, 14.0, 12.0, 14.0, 9.0, 0.0, 0.0, 0.0, 5.0, 14.0, 3.0, 10.0, 9.0, 0.0, 0.0, 0.0, 0.0, 8.0, 15.0, 14.0, 2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 14.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 9.0, 9.0, 3.0, 15.0, 4.0, 0.0, 0.0, 0.0, 12.0, 5.0, 1.0, 11.0, 8.0, 0.0, 0.0, 0.0, 7.0, 16.0, 16.0, 9.0, 1.0, 0.0]     with probs: [[3.60e-08 2.44e-01 1.36e-02 1.44e-02 1.53e-03 8.91e-10 1.03e-06 4.65e-02
  2.80e-01 9.43e-05]]
I predict            6 from the features [0.0, 0.0, 3.0, 13.0, 16.0, 7.0, 0.0, 0.0, 0.0, 1.0, 12.0, 16.0, 8.0, 0.0, 0.0, 0.0, 0.0, 2.0, 16.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 16.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.0, 16.0, 10.0, 11.0, 4.0, 0.0, 0.0, 0.0, 6.0, 16.0, 14.0, 13.0, 16.0, 3.0, 0.0, 0.0, 1.0, 11.0, 11.0, 2.0, 14.0, 10.0, 0.0, 0.0, 0.0, 2.0, 15.0, 16.0, 15.0, 6.0, 0.0]     with probs: [[1.57e-11 9.18e-27 2.04e-41 2.19e-04 6.69e-03 1.21e-05 9.95e-01 1.82e-34
  3.61e-47 3.83e-30]]
I predict       

<br>

#### We _could_ use cross-validation to find the "right"/"best" size and shape of the NNet...

<font color="Coral">But, let's not...</font>



In [29]:
#
# What shall we predict today?
print(COL_INDEX)
print()
print(COLUMNS)



{'pix0': 0, 'pix1': 1, 'pix2': 2, 'pix3': 3, 'pix4': 4, 'pix5': 5, 'pix6': 6, 'pix7': 7, 'pix8': 8, 'pix9': 9, 'pix10': 10, 'pix11': 11, 'pix12': 12, 'pix13': 13, 'pix14': 14, 'pix15': 15, 'pix16': 16, 'pix17': 17, 'pix18': 18, 'pix19': 19, 'pix20': 20, 'pix21': 21, 'pix22': 22, 'pix23': 23, 'pix24': 24, 'pix25': 25, 'pix26': 26, 'pix27': 27, 'pix28': 28, 'pix29': 29, 'pix30': 30, 'pix31': 31, 'pix32': 32, 'pix33': 33, 'pix34': 34, 'pix35': 35, 'pix36': 36, 'pix37': 37, 'pix38': 38, 'pix39': 39, 'pix40': 40, 'pix41': 41, 'pix42': 42, 'pix43': 43, 'pix44': 44, 'pix45': 45, 'pix46': 46, 'pix47': 47, 'pix48': 48, 'pix49': 49, 'pix50': 50, 'pix51': 51, 'pix52': 52, 'pix53': 53, 'pix54': 54, 'pix55': 55, 'pix56': 56, 'pix57': 57, 'pix58': 58, 'pix59': 59, 'pix60': 60, 'pix61': 61, 'pix62': 62, 'pix63': 63, 'is_0': 64, 'is_1': 65, 'is_2': 66, 'is_3': 67, 'is_4': 68, 'is_5': 69, 'is_6': 70, 'is_7': 71, 'is_8': 72, 'is_9': 73}

Index(['pix0', 'pix1', 'pix2', 'pix3', 'pix4', 'pix5', 'pix6', 'pi

In [30]:
#
# Here we set up for a regression model that will predict 'sepallen'  (column index 0)
#
#   sepal length  'sepallen' (column index 0)  <-- our target for _regression_

# We will use
#
#   sepal width   'sepalwid' (column index 1)
#   petal length  'petallen' (column index 2)
#   petal width   'petalwid' (column index 3)
#   _and_
#   species       'irisnum'  (column index 4)    # No problem - we can use this as a feature!

print("+++ Start of data-assembly for feature-regression! +++\n")
# construct the correct X_all from the columns we want
# we use np.concatenate to combine parts of the dataset to get all-except-column 0:
#                     exclude 0  , include 1 to the end
for i in range(64):
    X_all = np.concatenate( (A[:,0:i], A[:,i+1:]), axis=1)    # includes columns 1, 2, 3, and 4

# if we wanted all-except-column 1:   X_all = np.concatenate( (A[:,0:1], A[:,2:]),axis=1)  # columns 0, 2, 3, and 4
# if we wanted all-except-column 2:   X_all = np.concatenate( (A[:,0:2], A[:,3:]),axis=1)  # columns 0, 1, 3, and 4
# if we wanted all-except-column 3:   X_all = np.concatenate( (A[:,0:3], A[:,4:]),axis=1)  # columns 0, 1, 2, and 4
# if we wanted all-except-column 4:   X_all = np.concatenate( (A[:,0:4], A[:,5:]),axis=1)  # columns 0, 1, 2, and 3
# (slicing is forgiving) 


    y_all = A[:,i]                    # y (labels) ... is all of column 0, sepallen (sepal length) 
#                                 # change the line above to make other columns the target (y_all)
print(f"y_all is \n {y_all}")
print() 
print(f"X_all (the features, first few rows) is \n {X_all[:5,:]}")


+++ Start of data-assembly for feature-regression! +++

y_all is 
 [0. 0. 0. ... 0. 0. 0.]

X_all (the features, first few rows) is 
 [[ 0.  0.  9. 14.  8.  1.  0.  0.  0.  0. 12. 14. 14. 12.  0.  0.  0.  0.
   9. 10.  0. 15.  4.  0.  0.  0.  3. 16. 12. 14.  2.  0.  0.  0.  4. 16.
  16.  2.  0.  0.  0.  3. 16.  8. 10. 13.  2.  0.  0.  1. 15.  1.  3. 16.
   8.  0.  0.  0. 11. 16. 15. 11.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.
   0.]
 [ 0.  0. 11. 12.  0.  0.  0.  0.  0.  2. 16. 16. 16. 13.  0.  0.  0.  3.
  16. 12. 10. 14.  0.  0.  0.  1. 16.  1. 12. 15.  0.  0.  0.  0. 13. 16.
   9. 15.  2.  0.  0.  0.  0.  3.  0.  9. 11.  0.  0.  0.  0.  0.  9. 15.
   4.  0.  0.  0.  9. 12. 13.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.]
 [ 0.  0.  1.  9. 15. 11.  0.  0.  0.  0. 11. 16.  8. 14.  6.  0.  0.  2.
  16. 10.  0.  9.  9.  0.  0.  1. 16.  4.  0.  8.  8.  0.  0.  4. 16.  4.
   0.  8.  8.  0.  0.  1. 16.  5.  1. 11.  3.  0.  0.  0. 12. 12. 10. 10.
   0.  0.  0.  0.  1. 10. 13.  3.  0. 

### Second, from the iris example create a _pixel-predicting_ &nbsp; NNet

Choose a pixel to predict!
+ It _can_ be #42 -- or choose another one?!
+ This will be _regression_, not classification
+ It will show off NNets' ability to generate or "hallucinate" pixels/digits/images/etc.!
+ The _digit dreaming_ problem will extend this further...

<b>Predict-a-pixel</b> (regression)...
+ As the penultimate part of this digits-analysis with NNets, 
+ create a regressor that predicts pixel 42 from the other 63 pixels!
+ Remember that pixel 42 will be `A[:,42]`
+ and, the other 63, plus the digit-species, will be `np.concatenate((A[:,0:42], A[:,43:]),axis=1)`
+ see the iris_modeler for an example for the irises' botanical features...

In [35]:
#
# Here we set up for a regression model that will predict 'sepallen'  (column index 0)
#
#   sepal length  'sepallen' (column index 0)  <-- our target for _regression_

# We will use
#
#   sepal width   'sepalwid' (column index 1)
#   petal length  'petallen' (column index 2)
#   petal width   'petalwid' (column index 3)
#   _and_
#   species       'irisnum'  (column index 4)    # No problem - we can use this as a feature!

print("+++ Start of data-assembly for feature-regression! +++\n")
# construct the correct X_all from the columns we want
# we use np.concatenate to combine parts of the dataset to get all-except-column 0:
#                     exclude 0  , include 1 to the end
X_all = np.concatenate( (A[:,0:42], A[:,43:]), axis=1)    # includes columns 1, 2, 3, and 4

# if we wanted all-except-column 1:   X_all = np.concatenate( (A[:,0:1], A[:,2:]),axis=1)  # columns 0, 2, 3, and 4
# if we wanted all-except-column 2:   X_all = np.concatenate( (A[:,0:2], A[:,3:]),axis=1)  # columns 0, 1, 3, and 4
# if we wanted all-except-column 3:   X_all = np.concatenate( (A[:,0:3], A[:,4:]),axis=1)  # columns 0, 1, 2, and 4
# if we wanted all-except-column 4:   X_all = np.concatenate( (A[:,0:4], A[:,5:]),axis=1)  # columns 0, 1, 2, and 3
# (slicing is forgiving) 

y_all = A[:,42]                    # y (labels) ... is all of column 0, sepallen (sepal length) 
#                                 # change the line above to make other columns the target (y_all)
print(f"y_all is \n {y_all}")
print() 
print(f"X_all (the features, first few rows) is \n {X_all[:5,:]}")


+++ Start of data-assembly for feature-regression! +++

y_all is 
 [16.  0. 16. ... 16.  0. 16.]

X_all (the features, first few rows) is 
 [[ 0.  0.  9. 14.  8.  1.  0.  0.  0.  0. 12. 14. 14. 12.  0.  0.  0.  0.
   9. 10.  0. 15.  4.  0.  0.  0.  3. 16. 12. 14.  2.  0.  0.  0.  4. 16.
  16.  2.  0.  0.  0.  3.  8. 10. 13.  2.  0.  0.  1. 15.  1.  3. 16.  8.
   0.  0.  0. 11. 16. 15. 11.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
   0.]
 [ 0.  0. 11. 12.  0.  0.  0.  0.  0.  2. 16. 16. 16. 13.  0.  0.  0.  3.
  16. 12. 10. 14.  0.  0.  0.  1. 16.  1. 12. 15.  0.  0.  0.  0. 13. 16.
   9. 15.  2.  0.  0.  0.  3.  0.  9. 11.  0.  0.  0.  0.  0.  9. 15.  4.
   0.  0.  0.  9. 12. 13.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.]
 [ 0.  0.  1.  9. 15. 11.  0.  0.  0.  0. 11. 16.  8. 14.  6.  0.  0.  2.
  16. 10.  0.  9.  9.  0.  0.  1. 16.  4.  0.  8.  8.  0.  0.  4. 16.  4.
   0.  8.  8.  0.  0.  1.  5.  1. 11.  3.  0.  0.  0. 12. 12. 10. 10.  0.
   0.  0.  0.  1. 10. 13.  3.  0

### Permute!

<font size="-2">I like this because it adds an element of randomness to the whole process...</font>

In [36]:
#
# we scramble the data, to give a different TRAIN/TEST split each time...
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("target values to predict: \n",y_all)
print("\nfeatures (a few)\n", X_all[0:5,:])

target values to predict: 
 [ 0. 14.  0. ... 12.  0. 12.]

features (a few)
 [[ 0.  0.  0.  1. 14. 13.  1.  0.  0.  0.  0.  1. 16. 16.  3.  0.  0.  5.
  11. 15. 16. 16.  0.  0.  0.  4. 15. 16. 16. 15.  0.  0.  0.  0.  0.  8.
  16.  7.  0.  0.  0.  0. 10. 16.  3.  0.  0.  0.  0.  0.  8. 16.  6.  0.
   0.  0.  0.  0.  2. 13. 15.  2.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   0.]
 [ 0.  0.  0. 11. 16.  2.  0.  0.  0.  0.  7. 16.  8.  2.  0.  0.  0.  0.
  15.  7.  0.  0.  0.  0.  0.  0. 16.  4.  3.  1.  0.  0.  0.  1. 16. 16.
  16. 16.  4.  0.  0.  0. 12.  4.  6. 12.  0.  0.  0. 10. 16.  5. 10. 15.
   0.  0.  0.  2. 11. 16. 12.  8.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.
   0.]
 [ 0.  1.  9. 16. 16. 12.  1.  0.  0.  0.  7.  8. 10. 16.  9.  0.  0.  0.
   0.  0.  9. 16.  4.  0.  0.  0.  5. 13. 13.  3.  0.  0.  0.  0. 13. 16.
   8.  0.  0.  0.  0.  0. 11. 16.  8.  0.  0.  0.  0.  3.  5. 14. 15.  0.
   0.  0.  0. 10. 16. 11.  4.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.
   0.]
 [ 0.  0.  4. 

### Split into training and testing sets

We'll stick with 80% training, 20% testing...

In [37]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)})")
print(f"y_test: {y_test}\n")
print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)})")
print(f"y_train: {y_train}\n")
print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows

training with 1414 rows;  testing with 354 rows

Held-out data... (testing data: 354)
y_test: [ 0.  0. 16.  0. 12. 10.  0.  0.  5. 13.  0.  0.  8. 14.  0.  6.  5.  2.
 16. 16.  0.  0. 11. 16. 14.  8.  0. 16. 13.  0.  0. 12.  0. 12. 10. 14.
  2.  2. 12. 16. 12.  2.  1. 16.  0.  0. 12.  4. 16. 12.  0.  0. 16. 16.
  0.  0.  0.  0.  8.  3.  8. 15. 10. 16. 16.  0.  3. 14. 16. 14.  9.  6.
 13. 10. 13. 16. 15. 10.  0.  0. 15. 16.  0.  0. 15. 16.  8.  0.  0. 15.
  1. 12. 16. 15. 11.  9. 16. 16.  0. 15. 15. 10.  6.  5. 16. 12. 16.  0.
  7. 13.  6.  2.  0. 16. 13.  0.  2.  0.  0. 16. 15.  8. 16.  0.  0. 15.
 15.  4. 10.  0.  2.  1.  0.  4.  4. 16. 16.  0. 15. 16. 16.  0.  0.  2.
  0.  0. 16. 16.  0. 15.  2. 16. 16.  0.  0. 15.  0.  3. 15. 14.  0. 15.
 16. 16. 11.  0. 13.  2.  0. 16. 14. 16.  0.  0.  0. 13.  0.  0. 10.  0.
  4.  3. 16.  0.  0. 12.  0.  1. 16.  0.  0.  0. 12.  0. 12.  8.  0. 15.
  0.  8. 16. 10.  1.  0.  8. 16.  0.  2.  4.  0.  0.  0. 12.  0. 11.  0.
  8. 11. 16. 12.  8.  9.  0.  

### It's a nnet - this time, we _should_ use a <u>Scaler</u>

<font size="-2">Note that, for our <u>own</u> neural nets, this is performed by our senses:
+ our sense of hearing scales sounds from whispers to shouts... 
    + ... into a single amplitude for interpretation. 
    + and, we keep the scale itself as an additional signal!
+ similarly, our visual system scales across many orders of magnitude of brightness
    + plus, our eyes can "adapt" to low light (and, less, to bright-light )
+ less dramatically, for taste, touch, and smell...
+ this scaling 

In [38]:
#
# for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
#    This is done through the "StandardScaler" in scikit-learn
#
from sklearn.preprocessing import StandardScaler

USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    scaler = StandardScaler()
    scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
else:
    # this one does no scaling!  We still create it to be consistent:
    scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
    scaler.fit(X_train)  # still need to fit, though it does not change...

scaler   # is now defined and ready to use...

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Here are our scaled training and testing sets:

X_train_scaled = scaler.transform(X_train) # scale!
X_test_scaled = scaler.transform(X_test) # scale!

y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler

# reused from above - seeing the scaled data 
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

# reused from above - seeing the unscaled data (inverting the scaler)
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler)

                                                    input  ->  pred   des  
[ 0.   -0.34 -0.89  0.26 -0.44 -0.85 -0.41 -0.13 -0.06 -0.63  0.28 -1.5
 -0.66  0.28 -0.51 -0.13 -0.05 -0.73  0.01  0.54  0.64  1.14 -0.55 -0.12
 -0.04 -0.78 -1.29  0.89  0.98  1.43  0.73 -0.03  0.   -0.67 -1.19 -1.44
 -1.74  0.22  2.01  0.   -0.06 -0.53 -1.12 -1.21 -0.56  1.73 -0.09 -0.03
 -0.4  -0.98 -1.07 -1.01  0.86  1.47 -0.21  0.   -0.3  -0.7  -0.27  0.65
  1.54  0.72 -0.19 -0.32] ->    ?    0.0                  
[ 0.    1.99  2.27  0.98  0.96  1.44  1.11 -0.13 -0.06  2.18  1.02 -0.24
 -0.87 -0.05  0.33 -0.13 -0.05  1.76  1.06 -0.85 -1.15 -1.27 -0.55 -0.12
 -0.04  0.17  1.12  0.72 -1.47 -1.3  -0.62 -0.03  0.   -0.67  0.07  1.11
  0.29 -1.49 -0.82  0.   -0.06 -0.53  0.75  1.33 -0.74 -0.8  -0.09 -0.03
 -0.4  -1.15  0.28  1.26 -0.46 -0.77 -0.21  0.    4.2   2.05  0.89 -0.78
 -1.16 -0.51 -0.19 -0.32] ->    ?    0.0                  
[ 0.   -0.34  1.    0.26 -2.32 -1.03 -0.41 -0.13 -0.06 -0.63  0.28  1.02
 -0.

### Create and train the model

Note that hidden_layer_sizes is an important parameter.
+ for this hw, we're simply trying things out
+ no need to optimize via cross-validation

In [39]:
#
# MLPRegressor predicts _floating-point_ outputs
#

from sklearn.neural_network import MLPRegressor

nn_regressor = MLPRegressor(hidden_layer_sizes=(6,7), 
                    max_iter=500,          # how many training epochs
                    verbose=True,          # do we want to watch as it trains?
                    shuffle=True,          # shuffle each epoch?
                    random_state=None,     # use for reproducibility
                    learning_rate_init=.1, # how much of each error to back-propagate
                    learning_rate = 'adaptive')  # how to handle the learning_rate

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train_scaled, y_train_scaled)
print("++++++++++  TRAINING:   end  +++++++++++++++")
print(f"The (squared) prediction error (the loss) is {nn_regressor.loss_:<6.3f}")
print(f"And, its square root:         {nn_regressor.loss_ ** 0.5:<6.3f}")
print()



++++++++++  TRAINING:  begin  +++++++++++++++


Iteration 1, loss = 19.85190978
Iteration 2, loss = 7.83506333
Iteration 3, loss = 5.35299624
Iteration 4, loss = 5.13478546
Iteration 5, loss = 4.28952321
Iteration 6, loss = 3.78917345
Iteration 7, loss = 3.19606827
Iteration 8, loss = 3.02012149
Iteration 9, loss = 2.75537042
Iteration 10, loss = 2.57323314
Iteration 11, loss = 2.59950674
Iteration 12, loss = 3.09948717
Iteration 13, loss = 3.35692443
Iteration 14, loss = 2.55849633
Iteration 15, loss = 2.33794164
Iteration 16, loss = 2.39242111
Iteration 17, loss = 2.25271322
Iteration 18, loss = 2.35125489
Iteration 19, loss = 2.24420683
Iteration 20, loss = 2.26750061
Iteration 21, loss = 1.98619496
Iteration 22, loss = 1.84353423
Iteration 23, loss = 1.92068411
Iteration 24, loss = 1.82771427
Iteration 25, loss = 1.71917591
Iteration 26, loss = 1.99873223
Iteration 27, loss = 1.86364469
Iteration 28, loss = 1.99954836
Iteration 29, loss = 1.76847479
Iteration 30, loss = 1.7651814

### Let's test!  

Testing is different for regression!  
<font size="-1">
+ it's floating-point, so it's no longer "right" or "wrong"
+ instead, the _difference_ is what matters
+ in fact, the <u> _absolute difference_ </u> is usually what matters: </font>

In [43]:
#
# how did it do? Try out the TEST data...
#

def ascii_table_for_regressor(Xsc,y,nn,scaler):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(Xsc) # all predictions
    Xpr = scaler.inverse_transform(Xsc)  # Xpr is the "X to print": unscaled data!
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>35s} ->  {'pred':^6s}  {'des.':^6s}   {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # Xpr = Xsc   # if you'd like to see the scaled values
        print(f"{Xpr[i,0:2]!s:>35s} ->  {pred:<+6.2f}  {desired:<+6.2f}   {result:^10.2f}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # Xpr = Xsc   # if you'd like to see the scaled values
        print("The predicted pixel is "f"{pred:<+6.2f}") 

    print("\n" + "+++++   +++++   +++++           ")
    print(f"average abs diff error:   {error/len(y):<6.3f}")
    print("+++++   +++++   +++++           ")
    
#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor,
                          scaler)   # this is our own f'n, above
print(f"{'des.':^6s}")


                             input  ->   pred    des.     absdiff  
                            [0. 1.] ->  +0.26   +0.00       0.26   
                            [0. 0.] ->  +1.14   +0.00       1.14   
                            [0. 0.] ->  +14.14  +16.00      1.86   
                            [0. 0.] ->  +0.26   +0.00       0.26   
                            [0. 0.] ->  +8.87   +12.00      3.13   
                            [0. 0.] ->  +8.35   +10.00      1.65   
                            [0. 0.] ->  +0.26   +0.00       0.26   
                            [0. 0.] ->  +0.26   +0.00       0.26   
                            [0. 0.] ->  +6.72   +5.00       1.72   
                            [0. 0.] ->  +14.06  +13.00      1.06   
                            [0. 0.] ->  +0.26   +0.00       0.26   
                            [0. 0.] ->  +0.26   +0.00       0.26   
                            [0. 0.] ->  +6.85   +8.00       1.15   
                            [0. 5.] ->  +14.55  